### PR TITLE
[Semi-modular] Undead Quirk

### PR DESCRIPTION
**Pull request by Stalkeros2**
## About The Pull Request
Spiritual and frankly factual port of https://github.com/Bubberstation/Bubberstation/pull/761
Adds an undead quirk that applies the fake death trait to you. Costs zero points.
image
image
Also did a slight nonmodular edit to fix it from not displaying the SSD timers.

## How This Contributes To The Nova Sector Roleplay Experience
Lets people roleplay as non-vampiric undead or William Afton wannabes when paired with the Entombed quirk or whatnot.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl: Stalkeros
add: Added 'Undead' quirk that lets you LARP as (you won't believe it) the undead.
/:cl:

### CODE REVIEW

**Comment by W4rd3nn** [comment]
Good change for RP purposes. And to pre-empt the "bro undead are fantasy", there's plenty of reasons why someone may appear to be dead but not be, especially in the far future of SS13.

**Comment by nikothedude** [comment]
> didn't bubber revert this one
> 
> edit: they did, bugs and too memey. i agree. it should be vet locked at the very least.

bugs? memey? all it does is add TRAIT_FAKEDEATH. i think its fine

**Comment by nikothedude** [comment]
though there are some balance concerns regarding how it hides your health bar to medhuds

**Comment by Stalkeros2** [comment]
> bugs

I fixed it. It didn't show SSD timers beforehand on their end. It does here.
> memey

I've reflavored it. That was literally because of it being named 'Dead Inside'. As you can see, it's not named 'Dead Inside'.
> vet locked 

Fuck no.

**Comment by Stalkeros2** [comment]
> balance

Really don't care.

**Comment by Zergspower** [comment]
How does this show on a crew monitor? I added the flag for death in the last update I did do it rather than relying on maths

**Pull request closed without merging**
