### PR TITLE
Interlink station Modernization

### PR DESCRIPTION
**Pull request by FieryTech**
## About The Pull Request

I often felt like the Interlink was rushed and lacked in many details that could make it feel like a modern mapping. This proposal aims at the modernization of the Interlink with expanded living areas, a more "airport" feel, a small shop, better dormitories and an arrival section that was better fitted for the end-of-round.

## How This Contributes To The Nova Sector Roleplay Experience

A good roleplay environment often help in the general quality of the scenes that can take place in it.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
StrongDMM-2024-05-08 15 30 53

</details>

## Changelog
:cl:
add: A whole new Interlink station!
del: The old Interlink station.
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
What's the point of the station's bar and kitchen if you're just going to add it to the interlink

I'm pretty sure the purpose of the interlink is to be a safe space for people who want to ERP, chat, or dress up and also a place where cryo/clock out exists if they ever get destroyed. Not as a replacement for service.

I think prettying up the interlink and expanding the dorms is fine but you should not make the kitchen/bar available to the roundstart interlink.

**Comment by GoldenAlpharex** [comment]
This PR removes a lot of rooms in the interlink, which isn't something we want, as it was there to provide a safe alternative to dorms for those that want that.

The bar and the kitchen being only accessible on the round-end side was intentional, as it wasn't intended to allow people to skirt the real on-station bar and kitchen, and work on the Interlink instead.
I also feel like there's a bit less usable space in this than there was on the Interlink previously? It's hard to say, I haven't seen it in person, but that's my instantaneous hunch.

The room with the vendors should either be close to the bathrooms or have some changing rooms included, otherwise it's really awkward if your character understandably doesn't want to undress in front of others.

**Comment by sqnztb** [comment]
Before I get into my list of complaints, I am going to preface this by saying that I am fully aware that some of the things I am going to complain about are present in the current iteration of the Interlink.

While the total number of tiles is the only ~200 lower than the current interlink, It definitely feels off. Three less dorm rooms. The end of round area is super small and only has just the medical and little park areas to go into without having the shutters opened. Giant open construction area that the captain and NT rep are the only ones who can access? A cap/ntrep only meeting hall? Also the office has an *actual NT Rep and Blueshield locker set*. No. Also a little confused about using metal foam as a wall filler? Why wouldn't you just fill that in with walls? Looks weird from the hall. The trees right in front of the interlink shuttle block vision of the tiles in front of the door, combined with the railings next to the fake stairs to funnel everyone into entering from direct south will be annoying.


I'll echo the sentiments about Interlink not needing a bar and kitchen. For review purposes: there's shutters for the bar counter, for some reason, with no way to trigger them. Kinda ugly. Boozeomat is pixel shifted over into the wall which means you cannot move onto this tile. 
image

Also active turfs because you put in `/airless` reinforced floors.
image


I don't think this take on the interlink is any worse than the current design, but I don't think it's any better.

**Comment by Hemlock32** [comment]
I think this interlink looks aesthetically better than the current one, but, needs some improvements in functionality to be on parity with the current one

Also personal request, more disposals, especially around locations people can spawn, and, a pushbroom somewhere, like how the current one has a janitorial closet with one.

**Comment by FieryTech** [comment]
I'll try to answer every comment:
- Yes, the expanded kitchen and bar may compete with the station one, but I could cut the supply for those rooms. With no means to have products or beverages outside of the few ones that will be provided, they still are going to need to go on-station. It mostly was intended as RP spots, and not gameplau spots.

- The arrivals area is small, but the shutters are locked behind brig access. That means way more people than the captain, NT rep and cyborgs can open it and access the upper areas. They aren't locked into it like they used to unless security wants to slap people.

- For the shop, I could add a changing room to it. I still am decorating the place.

- The construction area is a TODO for me, I didn't have any idea about what to place there yet.

- I'll modify the map with the various bugs and such people found.

- I plan to remove the classroom-like CC room and switch the access to command too, after feedbacks.

If you think this is incompatible with our current policy about the Interlink (mostly the arrivals / departures separation), no biggies, that PR also was meant as a training for me since it's my first.

**Comment by SomeRandomOwl** [comment]
I personally disagree with the walls specifically, they need to be indestructible walls. Because from an admin perspective, someone can and WILL attempt to break into the departures shuttle and just vandalize it or something. Thats potential tickets that can happen and can be prevented. From what I'm aware though, we 'Technically' don't have any indestructible walls that uses our normal wall sprites. I could probably make a separate pr to add those in solely for mapping purposes to have nicer looking walls that are indestructible.

Also another personal gripe of mine is, we need to get rid of that damn fence on the interlink, its not actually indestructible, someone determined enough can just break it.

**Comment by FieryTech** [comment]
@SomeRandomOwl The walls are indestructible ones, but with a more normal skin.
For the fence, I would say there is no way to make things 100 % tider proof. Maybe by making the zone being unable to be teleported in, like the actual CC zone?

**Comment by FieryTech** [comment]
Progress so far:

StrongDMM-2024-05-13 22 13 57

TODO:
- Expand arrivals with a small library / cafe?
- Find something to do with the placeholder engineering section.
- Add more dorms?

**Comment by FieryTech** [comment]
Last batch of decoration with:
- General dorms improvement.
- Bits and things.
- Polishing.

And finally, a full scale test on my side:
<details>
<summary>Screenshots/Videos</summary>

Capture d'écran 2024-05-16 094314
Capture d'écran 2024-05-16 094357
Capture d'écran 2024-05-16 094436
Capture d'écran 2024-05-16 094515
Capture d'écran 2024-05-16 094604
Capture d'écran 2024-05-16 094619
Capture d'écran 2024-05-16 094631
Capture d'écran 2024-05-16 094958
Capture d'écran 2024-05-16 095018
Capture d'écran 2024-05-16 095043
Capture d'écran 2024-05-16 094226
Capture d'écran 2024-05-16 094238
Capture d'écran 2024-05-16 094302

</details>

**Comment by Aether217** [comment]
I think it's a good direction, considering interlink is used for 3 hours by some people while arrivals is used for 2-3 minutes most of the time, with the exception of the round end delays.

As for some feedback:
-I'd turn the NTC/Blushield office into some generic ones so everyone can use them, those two aren't supposed to linger on the interlink anyway.
-replace the trees below the interlink-arrivals shuttle with either just benches or nothing, that area sometimes becomes very high traffic, especially with the round modifier that spawns everyone in the interlink. The trees can go to the sides or be replaced by some bushes.
-The placeholder area could become either a proper library with booksshelves and some desks or a play room with card decks, paper, a round table or two, arcade machines and some other nerd related things.

**Comment by Zergspower** [comment]
eh nah, leave the NTC/BS offices - a couple universal ones would be nice however.

**Comment by FieryTech** [comment]
In relation to the last commit, and to answer comments;
StrongDMM-2024-05-16 23 47 13

**Comment by honkpocket** [comment]
> someone can and WILL attempt to break into the departures shuttle

?

image

**Comment by FieryTech** [comment]
> > someone can and WILL attempt to break into the departures shuttle
> 
> ?
> 
> image

When the map is loaded server-side, and during the round, the shuttle is docked and the blast doors are open.
That's probably what they meant.

**Comment by zeroisthebiggay** [comment]
> When the map is loaded server-side, and during the round, the shuttle is docked and the blast doors are open. That's probably what they meant.

you can break into the escape shuttle whenever. the chainlink fences on the interlink can be broken with a toolbox

**Comment by unit0016** [comment]
> you can break into the escape shuttle whenever. the chainlink fences on the interlink can be broken with a toolbox

already fixed; see #2319. Not sure if this forwards the changes from there

**Comment by theselfish** [comment]
This is my same issue with ghost roles and other such filler.

The round is on the station. The station should be the focus of the round. Having the extra dorms is fine because people are either continuing a scene from last round, planned something, or are going there because the on-station jobs are full.

Most players gravitate to the bar. There's even a term for it; Bar RP. The station has, at round start, two bars. The regular one and the Maint one. Adding a third will just lead to the bartender's content being stolen with zero effort. You at least need to get supplies to make the Maint Bar not look like a tip.

The Kitchen is whatever, It seems to start with no meat, or anything to actually run the kitchen so the Chef will be safe, though it makes the space somewhat useless, just a facade.

Adding other spaces, fine, whatever. But stealing content from jobs that only function with other people is bad, actually.

**Comment by FieryTech** [comment]
> Most players gravitate to the bar. There's even a term for it; Bar RP. The station has, at round start, two bars. The regular one and the Maint one. Adding a third will just lead to the bartender's content being stolen with zero effort. You at least need to get supplies to make the Maint Bar not look like a tip.

I mostly followed what already exists in the current Interlink, a salon and cafe, but I can see what would be the problem here.

I see two solutions: Removing the dispensers and only placing a few bottles of random booze on the table, or making it a Space Starbuck / Arcade area. And I like the idea of an arcade with pizza and stuff like on Blueshift.

Best to wait and see what the maintainers think of it? Not a big change to make.

**Comment by TetrakoHateThis** [comment]
Can't say I understand the need for an expansive kitchen/cafe when it has literally nothing in terms of supply and no way to resupply itself without station commuting...

**Comment by Jolly-66** [comment]
I will attempt to give this a looksie this week.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Sorry for the delay, but I discussed this with the other maptainers on hand and this is what we've deduced,

The post-round area needs to be fleshed out more. There isn't much going on, and would require someone to unlock the northern portion of the Interlink. The Interlink shuttle dock should be capable to entertain and keep the crew happy until the next shift (or until the server reboots).

In the same-ish area, there is a garden with windows. You should *really* replace them in favor of fences. It looks odd, honestly.

The bar and kitchen cannot stay. Moving them to the shuttle dock is fine, but they cannot be super decked out and crazy.

The few bits of firelocks around are, okay? But they feel out of place. There's not fire alarms (more importantly, there are no air alarms to control them). Replacing them with shutters is fine otherwise.

The hedges need to go as well, they're in planters and kinda ruin the aesthetic. This isn't your fault at all, we truly do lack much foliage options.

Please remove the maint loot spawners from the shop.

The fake arrivals shuttle itself is a wee bit too big, please consider sizing it down. The previous size should work fine.

Cryo is missing a timeclock, this is essential.

There are missing arrival shuttle monitors as well.

You need to redesign dorms. The whitespace (metal foam) shouldn't exist, and if it does, should be utilized well in designs.

Windows need **plating** under them, regardless of whatever type they are.

---

My minor comments/nits,

I would like to see cryo in its own room. Whether this is done or not is not a big deal, I'll merge this regardless of where cryo is.

Try to flesh out the disposals are a little more, it feels very shoe-horned in. I'm not asking for a full fledged disposals room, but something more than whats currently there would be better.

I will say, I do like how cozy this looks, it has a more industrial look which isn't too bad. Good job otherwise.

**Pull request closed without merging**
