### PR TITLE
[Modular] Moves cameras, railings and lights below the mob layer

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

This moves the layer that cameras lights and railings are on to be below the mob layer so that when someone pixel shifts against them they don't render onto of the mob. 

The only issue with this is with railings if you occupy the same square as them they will render below you, but i think...that is manageable because them rendering above you isn't as good either.

The reason cameras are on the same as the mob layer is for the sheer fact that they still render underneath the player mob, but still on-top of the light, as having it on the same layer as a light will occur in the light rendering ontop of the camera which doesn't look right in instances where cameras and lights share tiles

## How This Contributes To The Nova Sector Roleplay Experience

People can lean against walls without having a camera on their face

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/NovaSector/NovaSector/assets/2568378/97190f9c-3c88-4557-a529-02759de8c5f1
  
</details>

## Changelog

:cl:
qol: Altered the layer of lights and cameras to make them render below the mob layer so you can pixel shift against a wall and not have cameras ontop of your sprite
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
cameras and lights are absolutely above the spaceman, and this is going to make south facing railings look terrible

**Comment by SomeRandomOwl** [comment]
There is no other way around them rendering and playing nicely with pixel shift which is the whole goal with this i was considering removing the railings change though its like voth ways is bad

**Comment by Iamgoofball** [comment]
this has to be fixable in a reasonable way
@LemonInTheDark ideas?

**Comment by LemonInTheDark** [comment]
uhhh, do wallening. that or like, maybe shift the mob's physical position down with pixel_y/inverse pixel_z so it renders above the cameras temporarily. idk why you'd need to do this with railings that makes no sense

**Comment by SomeRandomOwl** [comment]
going to see if i can impliment this

**Pull request closed without merging**
