### PR TITLE
Disabling synth wounds code

### PR DESCRIPTION
**Pull request by delingar**
## About The Pull Request
Disabled all synth wound code.

Synth chemicals are not touched, except coagulant effects, due to lack of synth wounds.
## How This Contributes To The Nova Sector Roleplay Experience

Imo synth's wounds at current form are Biggest. PIECE. **OF DOGSHIT**. I appreciate all that work, that niko made, but, synths are more vulnarable then common human and their reskins. Wounds can appear every second punch or every first sharp weapon slash. Elecrical damage is the worst wound from all synth wounds. If synth is bad guy, get chased by security or roboticists are newbies and sillies, he will inevitably DIE, because electrical slashes appear faster, then synth fixes this wound.
There're alot of other ways to get synth down.
From ion rifle to ion scatter slug that can be made easily or chemicals, that lower/raise body temperature. EMP effect can be countered only by nukie and assault op.

Synths have enough MAJOR negatives(imo) without those wounds: Disabled chemical metabolising of almost all chemicals, Disabled genetics, GIANT vulnerability to all levels of EMP(one shot from ion rifle and synth is down and disoriented cuz eyes emp effect) that locks like 30% of bad guys equipment, low temperature resistance(What sense of being space proof if you're dying much faster?), alternate food system (can't get mood buffs from chef's food)
There's only few ways to make synths more robust/playable for combat roles: Disabling wounds again, Adding EMP-protection implant to RnD/Cargo/Opfor menu, Adding specie-exclusive expensive positive quirk, that can disable wounds for synths.    

## Proof of Testing
I just removed code. Do you really think it needs testings?

## Changelog
:cl:
del: Disabled synth wounds
/:cl:

### CODE REVIEW

**Comment by honkpocket** [comment]
This is the worst way to handle code contributions and I am sympathetic for the developer who I know will see and read this. How disappointing.

**Comment by nikothedude** [comment]
hello synth wound creator here

you cannot do this without also increasing the brutemod/burnmod of synths to 1.3

this is why synth wounds were created my friend, to bring that mod back to normal, since they were put that high as synths _could not get wounds_

**Comment by nikothedude** [comment]
also yes you still need to test your code

**Comment by nikothedude** [comment]
regardless. why straight remove them? if you want a better solution, and if wounds really are in this bad a state (i agree theyre a bit overtuned), you could always pull the balance lever of increasing their wound threshold t o just make them rarer

**Comment by delingar** [comment]
> regardless. why straight remove them? if you want a better solution, and if wounds really are in this bad a state (i agree theyre a bit overtuned), you could always pull the balance lever of increasing their wound threshold t o just make them rarer

They must be totally overhauled imo, cuz even if electroshock wound will appear much rarer, it's still can kill synth fast enough, so even roboticist will not save patient, at T2+ wound tier

**Comment by nikothedude** [comment]
> > regardless. why straight remove them? if you want a better solution, and if wounds really are in this bad a state (i agree theyre a bit overtuned), you could always pull the balance lever of increasing their wound threshold t o just make them rarer
> 
> They must be totally overhauled imo, cuz even if electroshock wound will appear much rarer, it's still can kill synth fast enough, so even roboticist will not save patient, at T2+ wound tier

that certainly doesnt sound like something that needs a total overhaul
more a tweak of values

regardless this pr finally got me to get up off my ass to implement a long-planned nerf to electrical damage so good work

**Comment by SomeRandomOwl** [comment]
Removing code is counter productive to contributing, fix issues and add things. flat out removal is not the way to do things. Refactoring and fixing things are better than flat removing features because you got frustrated with them.

**Pull request closed without merging**
