### PR TITLE
ports HUD changes from shiptest slash bubber slash citadel

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

ports a few HUD sprites which originate from shiptest and have slowly been modified to be sleeker in order to fit better with TG's general art style philosophy as well as fit better when used with upscaled player models

additionally this changes departmental guard secHUDs aside from the corrections officer's to be departmentally colored secoff badges rather than random objects
like why is customs agent `. . !` what does that mean

relevant PRs
https://github.com/shiptest-ss13/Shiptest/pull/1469 < the proprietor
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15843 < the derivative
https://github.com/Bubberstation/Bubberstation/pull/280 < the port
https://github.com/Bubberstation/Bubberstation/pull/924 < the fix

## How This Contributes To The Nova Sector Roleplay Experience

i just think they're nicer looking
also the healthHUD is invisible when someone's at full HP and I think it's nice to actually be able to see people's faces when i'm in medbay

## Proof of Testing

image

***image not up to date, colors are very slightly darker now, please check the comments and the icondiffbot**

## Changelog

:cl:
image: security diagnostics and medical HUD overlays complete revamp
/:cl:

### CODE REVIEW

**Comment by SomeRandomOwl** [comment]
This looks...interesting? Personally though I'm not a fan of hudill5 and huddead, its too much of a departure of what we currently have rather than a touch up, especially since its the same icon as a death commando ID card iirc

**Comment by zeroisthebiggay** [comment]
> This looks...interesting? Personally though I'm not a fan of hudill5 and huddead, its too much of a departure of what we currently have rather than a touch up, especially since its the same icon as a death commando ID card iirc

the ill icon is for HMS and is already rarely seen
it's also a parallel of what it is currently being the friendly virus blue with a frown that seeps blood

the death skull is definitely a bit of a departure but all i can say to argue for it is the skull looks cool

**Comment by zeroisthebiggay** [comment]
> the hud being gone at full health is going to be confusing (there's already been plenty of bugs that make huds stop working/dissapear,

only the health **bar** is invisible when at full health, the badge is still fully visible; all that's changed is there's less screen clutter when near healthy people, and it's more easily recognizable at a glance when someone is injured `(the bar will show if someone has even one brute damage)`, also i'm fairly certain most if not all z-level related HUD bugs are currently fixed

> and how is that going to work with viruses?), 

see above
the health badge which handles the virus face is still completely visible at all times

> the dead sprite looks like the deathsquad ID icon,

this just feels like a nitpick, how often do you see a deathsquad ID to where you'd confuse it with the icon for someone being dead - one being handled by the secHUD, and the other by the medHUD no less, but two people've complained about it so i've reverted it back to the original

and honestly the "neon/pastel" colors hurt to look at.

image

i took the advice and toned down some of the colors, specifically the greens and yellows; reds are unaffected as they're typically used only when shit's really bad, so i don't think it's necessarily bad that they're eye-catching
*image is shows the old and new palette, but the PR body image isn't updated

**Comment by Iamgoofball** [comment]
>additionally this changes departmental guard secHUDs aside from the corrections officer's to be departmentally colored secoff badges rather than random objects

this is a bad change, departmental guards are not security and thus should not have the security officer job icon

**Comment by zeroisthebiggay** [comment]
> > additionally this changes departmental guard secHUDs aside from the corrections officer's to be departmentally colored secoff badges rather than random objects
> 
> this is a bad change, departmental guards are not security and thus should not have the security officer job icon

do you have any better suggestions because `. . !` does not convey anything
the closest if anything is sciguad with the black mesa badge but that's only coherent if you're in the know

**Comment by Iamgoofball** [comment]
even if ..! does not directly convey anything, it is a unique symbol that can be immediately recognized as a unique symbol by the casual observer who will then associate it with Customs Agent after shift clicking the person and seeing their ID card title

**Comment by GoldenAlpharex** [comment]
I'm sorry, but I don't really see these as an improvement or as a desirable change over what we already have. It obfuscates the job icons more, as Goof already stated, and otherwise makes the color far too similar from a quick glance, they don't stand out as much, I feel.

I don't think this is something we need, sorry.

**Pull request closed without merging**
