### PR TITLE
New sprite added to plushies.dmi

### PR DESCRIPTION
**Pull request by Rusuro**
Added plush_142 for Ckey:Rusuro to plushies.dmi

## About The Pull Request

This is the item I (Rusuro) have made to be my donator item. It is a plush version of my character, XAL-142 in her loadout outfit.

## How This Contributes To The Nova Sector Roleplay Experience

I think it would benefit the server by adding more to the list of items in character setup and loadout menu. I also think it would be a fun little addition as well as being something I paid to have access to.

## Proof of Testing

<details>

<summary>Screenshots/Videos</summary>
plush1

plush2

</details>

## Changelog
:cl:
add: Added new sprite to plushies.dmi
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
the plushie is inaccessable as just a sprite you need to add the item

**Comment by SomeRandomOwl** [comment]
This doesnt actually add the plushie, going to make this as a draft until such a point

**Comment by Rusuro** [comment]
> This doesnt actually add the plushie, going to make this as a draft until such a point

Alrighty. I Just want it to be added to the dmi for the time being. Still learning about all this and getting help from others. Currently (with ability to appeal) permachatbanned on the discord so it's a bit hard to get help.

**Comment by Rusuro** [comment]
> As others have said you'll also need to add the code for your plushie here:
> 
> https://github.com/NovaSector/NovaSector/blob/527e883d09197c715f5379141230b6cf47caf282/modular_nova/modules/customization/game/objects/items/plushes.dm#L653-L659
> 
> If you're unsure how to do that just look at the other example plushes and copy their format, most important thing is your icon state e.g. it should be `icon_state = "plush_142"`. The rest is up to you for how you want it to work.

Next time I get VS and my github client open on my PC, I will try to do this. Thank you!

**Pull request closed without merging**
