### PR TITLE
[MDB IGNORE] Rough Draft: Flandstation Episode II: The Automapper Strikes Back

### PR DESCRIPTION
**Pull request by Mintybea**
## About The Pull Request

This is a continuation of my current ongoing plan to port Flandstation from Beestation to Nova. Flandstation is an unconventional station with a vague (and I mean vague) resemblance to Birdshot. Most of the station post-conversion is 1:1 with its beestation counterpart, but some departments (science, medical, and bridge) have had major changes to be better suited for Nova's experience.

The original Skyrat PR can be found here --> https://github.com/Skyrat-SS13/Skyrat-tg/pull/21823

Fland designed by Pigeonverde, thank you for letting me make a port for Nova.

## How This Contributes To The Nova Sector Roleplay Experience

Flandstation is a colossal map with a variety of different places to both explore, and plenty of room for gimmicks. It has an extensive set of maints and an unconventional layout that isn't painful like Birdshot.

## Proof of Testing
The map is NOT DONE (this PR is up for testing and review porpoises)

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog
:cl: Pidgeonverde, Mintybea
add: Adds a new station, Flandstation, to the game! Also adds a new shuttle for Flandstation.
/:cl:

### CODE REVIEW

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Cursory review, mostly looking around.

<details>
<summary> Active Turfs</summary>
You have a handful of active turfs. What this means is, some turf(s) have different gas comps than surrounding turfs. This is an easy fix; if a turf with the same gas comp does not exist in code, make it.

---
*I'm not including all of them. However, you can find this information by going to the Debug tab, finding Mapping Verbs - Enable, Mapping tab and selecting `Show roundstart AT markers/list`.*

image

image

image

image

image

</details>

<details>
<summary> Cameras </summary>

Captains office is missing camera coverage.
image

Transfer cell lacks camera coverage.
image

Morgue.
image

Errr, I believe spessmen want to use the facilities without the spying eyes of AIs and the warden.
image

Same with bedrooms, even if its the HoS.
image

Blindspot in the prison.
image

Missing coverage.
image

Another blindspot.
image

Ditto.
image

image

image

Missing the holodeck cameras.
image

Blueshield office lacking coverage.
image

</details>

<details>
<summary> Intercom Range </summary>

Deadzones.

---

*I'm not going to include a lot, but you can check this out for yourself with the mapping debug verbs.*

image

image

image

image

image

image

</details>

<details>
<summary> Air Alarms </summary>
You're most likely going to have ot hand fix these which should be simple. If needed, I can help write an updatepaths for you to use. They just need their nudges to be corrected. 
----
*I may need to double check this since I'm still not used to the new air alarm sprites and do not know what their nudges are supposed to be.*
</details>

<details>
<summary> Atmospherics (non-department) </summary>

The `Check Plumbing` verb is not great, but it can be somewhat useful. There are a handful of disconnected atmospheric vents around the station (and probably more than just vents).

</details>

**Comment by zydras** [comment]
Alright! Let's start with a few things I've immediately spotted while trying out the map as an assistant:

<details>
<summary>Bad Access Codes</summary>
Auxiliary Mining Base is typically reserved for miners and engineering...

Screenshot (2494)
Upper Xenobio maints airlock has no access restrictions

Screenshot (2497)
Mech Bay shutters have no access restrictions

Screenshot (2498)
Engineering Lobby windoors lack access restrictions

Screenshot (2499)
Screenshot (2500)
Engineering storage windoor...

Screenshot (2502)
</details>
<details>
<summary>Misplaced tiles/objects</summary>
I Don't Think Sinks Go Like That!

Screenshot (2509)
Goof up at the Chaplain's office...

Screenshot (2511)
Bea I don't think using the funeral launch pad counts as a "departures lounge"

Screenshot (2512)

</details>
<details>
<summary>Design changes</summary>
Window above the computer is a little out of place and isn't aesthetically good looking

Screenshot (2495)
This mailroom feels like a medical area at first glance, I'd suggest using Yellow and Brown floor tile markings rather than blues.

Screenshot (2496)
Missing floor tile under this airlock

Screenshot (2493)
I wonder why you put a window here but it does feel a little out of place, _especially_ with the disposals bin right in front of it. Maybe just turn the shutter sideways?

Screenshot (2504)
Don't put maintenance mapping helpers on airlocks if they're on the pathway of the maint hallways... randomzied dead ends aren't too fun!

Screenshot (2508)

</details>

Overall, I think the map has a pretty... _strange_ layout? It feels like many departments are all over the place and some are _really_ out of reach unless you're specifically going there.

**Comment by Mintybea** [comment]
I won't be changing the layout of the departments themselves since that kind of takes away what makes Fland itself.

That being said I will work on these tonight.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Nits

I would go around, and its going to be painful, but a lot of wallmounts need to be converted to directionals. For the most part, this'll be very easy, some have vars edits which'll just add a bit of tediousness to it, but shouldn't be too hard.

<details>
<summary> Medical </summary>

Please use a maintenance define here.
image

Missing a pipe for cryo pipe loop.
image

Fire alarm on a window.
image

Shutter on a wall. Also move that cabinet to the wall to the left, and revert the nudge on the air alarm.
image

Follow Blueshift/VR for what to do for the dept sec offices. TLDR but remove any and all security adjacent things (including records consoles)
image

Massive nitpick but this doesn't look like a patient room.
image

Tile under this window.
image

You don't need two viro setups, remove the additional one.
Also replace the cuffs, or cut it down to one. A cable coil would be fine there to make cable cuffs, which are weaker.
image

Coroner needs the secure morgue trays.
image

This is a VERY tiny chem, the smallest out of any map we have currently.
To put it into perspective, this is almost HALF the size of Blueshift (135)
image

Get rid of that chem stuff for viro. If they need it, they should be contacting the chemists.
image

Random electrified window in CMO office.
image

Move the chem heater so it would be in interaction range. This way if someone is making chems they can man the desk while they're doing it.
image

2x2 wall :(
image

Another minor nit is, maintenance doors bordering maintenance need to have maintenance areas applied to them.

</details>

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
<details>
<summary> Service/Common areas </summary>

Use funeral parlor here.
image

Use regular library area here.
image

I think Hydro would benefit from having a hall facing entrance, considering its main entrance is.. tucked away in the service hall. Also remove that disk drive thing, we don't use it on /tg/ code.
image

Use bar backroom here.
image

Fix your chair orientation.
image

Please recolor these pipes to match the ones in the coldroom.
image

Another 2x2 :(
image

Not really a good idea to start with the barbershop closed round start. What if the barber late joins?
image

There is only one way to enter into this altar, which is very silly.
image

Give the public garden some hydro trays.
image

Replace common with fitness.
image

</details>

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
<details>
<summary> Cargo </summary>

Use the DEN area here.
image

Also the walls don't need to be secured.
image

This does not need to be defined as cargo bay, nearstation will suffice.
image

Please swap mining explore with something else, thats Lavaland area.
image

Ditto with medical. Remove any sec adjacent stuff.
image


</details>

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
<details>
<summary> Science </summary>

Remove robos morgue tray.
image

Ditto. No sec stuff.
image

Destructive scanner needs to be put in the lobby.
image

You need one master server to generate points.
image

Few things here,
Inconsistant with the medbay break room (the bathroom has no access defines),
The sink is backwards.
image

Where are the slimes?
image

Why is this an atmos ignore? Add vents.
image

The burn chamber is missing shutters.
image

This is not a circuits lab.
image

Use multi-airlock cyclers here.
image

Research console?
image

Weird place to put the scivendor.
image

This doesn't look lime a maintenance tunnel.
image

Gene should be secured (r-walls).
image

You should also audit the usage of r-walls in general in the department. If they border the main hall/maintenance, secure them. If they border an internal room (i.e robotics borders the circuits labs), they do not need to be secured between them. This does not apply to the server room however, they needs to stay secured.


</details>

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
<details>
<summary> Sec </summary>

You don't need to do this. Replace it with regular brig.
image

Use some of the armory spawner helpers. Also double check our AM templates for armories to make sure they're compliant in terms of gear.
image

Ditto. Don't do this.
image

Sec med does NOT need to be this decked out. Trim a lot of this please.
image

The prison feels very flaccid, but there really isn't anything you can do due to its position.
image


</details>

**Comment by Jolly-66** [comment]
I will be deferring engineering to Granite.

**Comment by sqnztb** [comment]
Alright so this is just a first pass of stuff that I noticed after a couple hours of looking around. huge props to @FlufflesTheDog for helping with this first pass.

<details><summary>engine room</summary>
- the first filter in the engine's waste should have nitrogen set as the default `filter_type` (look at another map for reference)
- two air alarms right next to each other in the engine room, kinda weird
- one length of omni pipe at the filter cans
- needs a couple extra gas meters for the different sections of the cooling loop
- one of the thermomachines is set to on/room temp by default.
- since the emitters are on the inner wiregrid, need to have some sort of easily accessible power generation since there's no power to them initially
- viewing port button doesn't work
</details>
<details><summary>turbine</summary>
- turbine's not connected to the computer
- turbine chamber feeds straight into main waste, should have it's own little waste pipe
- turbine smes is FED from the main grid. typically
</details>
<details><summary>gravity gen</summary>
- power feeds the apc and then into the smes. power should flow from main grid to the smes to the apc and stay in the room
- additionally the wire loops around through the windows, putting the smes on both input and output.
</details>
<details><summary>atmos</summary>
- missing a tile on the west side
</details>
<details><summary>ordinance</summary>
- no walls/doors for the burn chamber, immediately vents to space
- burn/freeze chambers are on separate areas (like the should be) but don't have APCs
</details>
<details><summary>sci breakroom</summary>
- decals over walls
- floating sink
- tinted+untinted windows mixed. do either one or the other.
</details>
<details><summary>teleporter</summary>
- shutter button doesn't work
</details>
<details><summary>dorms</summary>
- needs a "real" pool.
</details>
<details><summary>law office</summary>
- loose cables
</details>
<details><summary>hallway above tcomms</summary>
- loose decal?
</details>
<details><summary>vault</summary>
- "food crate"s
</details>
<details><summary>bridge</summary>
- safe has density, needs to be manually edited or moved somewhere else
- bridge teleporter shutter button
</details>
<details><summary>hop</summary>
- no photobooth
</details>
<details><summary>perma</summary>
- extra cryo console. cryo console was also flipped iirc
</details>
<details><summary>sec</summary>
- missing tiles in the lower entry
- holding cell flashes aren't linked to the right cells
- no photobooth
</details>
<details><summary>medical</summary>
- cryo - one pipe is wrong, it gets half hidden under a pipe (left side of the loop)
- operating room has ugly grey tiles
- orderly office has ugly grey tiles
- floating tube lamp on the fridge in the TC-OR junction
- chemistry - no ducts
- pharmacy - outfit closet not needed, no mass spectrometer, and there's 2 reaction chambers for the lower station
- medidrobe in maints?
- break room bathroom kinda weird with the south sink
- cable missing in the lower lobby area.
</details>
<details><summary>library</summary>
- lower corner, very dark
- there is an extra large art frame on the wall (facing east) which will overlap with the west-facing frames in the gallery
</details>
<details><summary>service</summary>
- hydro - double bumbles, loose wire in the backroom
- service hall - extra length of wire, one of which runs under the wall
- bar - boozeomat in the wall, south end is kind of dark
- cold room - very dark, stub pipe outside that doesn't connect to anything, and the weird pump running through the wall
- kitchen - needs a dehydrator
- barbershop - scrubber underneath table
</details>
<details><summary>cargo</summary>
- shuttle loading/unloading area very dark
</details>
<details><summary>arrivals area</summary>
- public garden - needs a seed extractor and a water source (puddle). there were SIX STRANGE SEEDS, SEEDLINGS, AND DEATH NETTLES HERE when I tested. if you keep the random seeds, use the stock spawners (don't varedit them) and remove the rare spawn seeds. optionally put static seed packets or a megaseed. a nutrimax would also be lovely.
</details>
<details><summary>disposals</summary>
- the only issue I noticed initially is aux tool storage and the arrivals hall both spit you out in the gateway because of the y junction there
</details>

**Comment by Mintybea** [comment]
Seeing as I was community banned, with no means of ever returning to the community after I left. I have no intent on continuing this project. It's been fun, see y'all somewhere else.

**Pull request closed without merging**
