### PR TITLE
Unapologetic Moth Buffs Vol. 1

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
How's it going. I was forced to make and play a moth as well as support moth content. There is a high-grade assassin lurking outside my complex and they will take the shot if I don't.

Anyway, this PR does two things because I only have the brainpower for two things.
image
You can't blame me for this one.

One, moths get inherent hardened soles. Let me show you something.
image
This is a normal moth with crazy-ass Signalis peglegs. She looks like a beaut.

image
Big shoe lmao.

So I'm making it to where they don't inherently need shoes.

Two, moths get transcendent olfaction. 
image
This is more of a lorely buff, because moths are highly sensitive to smells and pheromones and such.

## How This Contributes To The Nova Sector Roleplay Experience
Moths are kind of a nothingburger species outside of the jokes and the slim amount of mechanics they have, and I'm pleased to attempt unfucking that.
## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog
:cl:
add: Moths now have inherent Hardened Soles and Transcendent Olfaction. I couldn't think of a funny caption for this.
/:cl:

### CODE REVIEW

**Comment by OrionTheFox** [comment]
-1 for the phrase nothingburger, +1 because these traits fit moths pretty well and I enjoy seeing the species being more realistic

**Comment by Zergspower** [comment]
You've invoked the wrath of icebox CI

**Comment by SomeRandomOwl** [comment]
> Why don't you just take the hardened soles quirk if you want to not wear shoes? This is how we've done it for years?

especially since i think we removed quirk points

**Comment by Nerev4r** [comment]
Gonna redo this real quick.

**Pull request closed without merging**
