### PR TITLE
Nerfs Fragility By Buffing It; What?

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
You can now only pick up to 2x extra damage instead of 5x extra damage.

## How This Contributes To The Nova Sector Roleplay Experience
I'm terminally horribly exhausted of people that take the 5x multiplier because you can't even do surgery on them without risk of killing them; and there's been many meme characters that take practically every negative trait alongside it, like death degradation and frail and allergies and stuff. No more of that. I'm maybe open to 3x.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
It's one line.
</details>

## Changelog
:cl:
del: Fragility now only goes up to 2x instead of 5x.
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
If you dont like it... dont take it?
No need to ruin something for someone else just because you dont like it.

**Comment by Iamgoofball** [comment]
@MajManatee did you even read the opening post justification

**Comment by MajManatee** [comment]
Yes? If they want to not be able to be operated on, let them? This forces doctors to adapt, same as dealing with a plasma man would. Removing it because it inconveniences you, the person fixing them, is silly.

**Comment by HoodMilk** [comment]
The obvious solution is to force DNR on people who take a damage modifier above 2x :)

**Comment by Namwty** [comment]
I'm not a medical player, so I can't exactly judge if people like harder to treat patients or easy ones... to me it feels like 50/50 sometimes. ( Like some people like trying to patch up "entombed zero charge" patients, some absolutely hate it ).

But I always assumed that saw step does 40 dmg or something, if that's the case.... x5 is basically cooked, as expected honestly.


But again, I do know some medical players like "special cases", but I also know that some people dislike those. But let's be real, a surgery step shouldn't just be "execution" ( in normal situations at least ), regardless of what. It doesn't make sense IC anyhow... wtf does CMO just cut trough their head with a saw? Should medical staff IC just say "ahh... I just murdered a patient, expected outcome"?

**Comment by SomeRandomOwl** [comment]
Another solution is to make the modifier not apply specifically to surgery, or only apply to at most half damage because medical personal are trained to use their tools. They should be able to be gentle with their tools when taking care of patients no matter what their sensitivity to pain is. Can also make the pain modifier lessen if under the effects of stasis.

**Comment by lessthnthree** [comment]
Operating computer stops you from jabbing the wrong tool in them, it seems plausible it would also be able to stop a doctor from jabbing the tool if it would kill them. Could add that as a check.

**Comment by lessthnthree** [comment]
if we get a reduced speed/careful surgery mode, please also give a careless, fast mode that does more damage. 😎

**Pull request closed without merging**
