### PR TITLE
Space Ruin - Black Market Trader Balance pass

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

This one has been on my list for a few months but with the surgery n crap i just never got to it.

Simple:

Removes the two Alien tool spawns and replaces it with a single adv tool - i only ever meant for it to be 1 in the first place but the tools really should be find-only anyway.

Removes the Makarov and replaces it with a cycler - the Makarov's pretty powerful in its own sense, while it's also a perfectly fine starter weapon it kinda trivializes the role design too much. A cycler is just a stacked double barrel, sitting between a double barrel and the normal shotguns (max 4 inside vs 6 or 2 respectfully).

## How This Contributes To The Nova Sector Roleplay Experience

I made this role to be challenging, but i also gave it too many creature comforts in my last redesign so we're just dialing it back a little bit at a time until I'm happy with it. 

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
  
  
image

  
image

  
  
</details>

## Changelog
:cl:
add: Space ruin - Added an experimental tool to replace the alien tools for the BMD
add: Space ruin - Added a Cycler Shotgun to replace the Makarov
del: Space ruin - Removed the alien tools from the BMD Spawn as well as the Makarov
balance: Space ruin - Turned down the BMD Starter equipment
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
I thought the cycler was borderline non-functional? or just incredibly clunky.

**Comment by Zergspower** [comment]
> I thought the cycler was borderline non-functional? or just incredibly clunky.

image
just went through all the options - it works fine and i feel is a good middle between the two shotgun styles (i refuse to acknowledge the pistol)

**Comment by RatFromTheJungle** [comment]
> > I thought the cycler was borderline non-functional? or just incredibly clunky.
> 
> image just went through all the options - it works fine and i feel is a good middle between the two shotgun styles (i refuse to acknowledge the pistol)

it should be said that the cycler isn't 4, it's 8, it has 2 tubes, so it's 4+4

**Comment by Zergspower** [comment]
> it should be said that the cycler isn't 4, it's 8, it has 2 tubes, so it's 4+4, you use right click to swap the tube

When i tested it earlier it only fit 2 in each barrel

**Comment by Zergspower** [comment]
ok the cycler is indeed clunky, adorably clunky.

in any combination of 5 shells can be loaded into it, 3 and 2, 1 and 4 etc. but no more than 5 total can fit in it lmao - and you can unload them all from 1 tube

**Comment by MajManatee** [comment]
I'd love to use it, if it got a good once over to make it less horrid. Properly having 4 shells per tube and switching on a right click like god intended.

And you're telling me we have an aliens pulse rifle that's used nowhere??

**Comment by HoodMilk** [comment]
Cycler is clunky and painful to use, maybe giving them a regular laser gun would be better as its more fitting for a space role and doesn't use ammo.

**Comment by Zergspower** [comment]
> The BMD starts with a laithe, and can very easily print shotgun ammo. Frankly, I'd rather have a shotgun over a pistol. One of the most limiting factors to early pillaging is running out of my two mags of pistol ammo, plus there are plenty of ruins to get a Makarov or 1911.

the Makarov only needs iron for a box of ammo from the lathe, and it's fairly strong once you have a few of those.

i just made a weapon spawner with weights similar to the old armory spawner, with a carrot on the stick with a bulldog being a 1 weight.
image

**Comment by GreytideSkye** [comment]
Round last night, they couldn't find the cycler shotgun. Where's it _supposed_ to spawn? On that table?

**Comment by Zergspower** [comment]
> Round last night, they couldn't find the cycler shotgun. Where's it _supposed_ to spawn? On that table?

It's not always a cycler, it at random picks a gun in the list above

**Review by sqnztb — APPROVED** [review]

**Pull request merged**
