### PR TITLE
Adds differently layered alternate "cat, big" ears

### PR DESCRIPTION
**Pull request by chestlet**
## About The Pull Request
This PR adds an alternate version of the the "cat, big" ears, layered the same as the non-greyscale cat ears. The way the states were created in the dmi made it so that from the front the ears were layered below the hair, making them look bad outside of a few niche uses. However those niche uses DO exist, which is why this PR has been changed to add this version as an alternate.

## How This Contributes To The Nova Sector Roleplay Experience
More character variation, many people didn't even consider these ears an option because of how they're layered.

## Proof of Testing
<details>
  All images taken from character setup, set to high contrast colors to increase visibility.
<summary>Screenshots/Videos</summary>
 
ear preview

</details>

## Changelog
:cl:
qol: Added an alternate version of "cat, big" ears, which are layered above hair.
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
tysm

**Comment by zeratino** [comment]
please, keep the behind-hair ears as another, different type 

this fucks over the people who use this hair as that described “niche” function

**Comment by chestlet** [comment]
> please, keep the behind-hair ears as another, different type
> 
> this fucks over the people who use this hair as that described “niche” function

Yeah, sure! Let me do that real quick

**Review by GoldenAlpharex — APPROVED** [review]
Looks good to me!

**Pull request merged**
