### PR TITLE
[MIRROR] Removes night vision quirk

### PR DESCRIPTION
**Pull request by NovaBot13**
Original PR: https://github.com/tgstation/tgstation/pull/83356
-----
## About The Pull Request
This pr removes the quirk night vision from being selectable

## Why It's Good For The Game
Since the night vision rework this gives instead of the 3 tiles around you full soft vision in the darkness
Heres 2 screenshots to compare the difference.

This is what people without night vision see.
image

This is what people with night vision see.
image

Night vision does not define a character and is 100% client side.
this also turns antags like nightmares that hide in the shadows less scary and just make the envoirement boring when it comes to combat darkness vs light has 0 adventages because majority of the people run night vision antags who break lights to rely on this adventage just end up wasting time because everyone has inbuilt night vision

### CODE REVIEW

**Comment by Iamgoofball** [comment]
what if you guys just, y'know, didn't keep the quirk that completely negates darkness for certain players?

**Comment by CliffracerX** [comment]
> what if you guys just, y'know, didn't keep the quirk that completely negates darkness for certain players?

Because we've put effort into making night vision more interesting & because night vision isn't the end-all be-all powergame tool here that it is on TG.

**Comment by SomeRandomOwl** [comment]
> what if you guys just, y'know, didn't keep the quirk that completely negates darkness for certain players?

We have quirks that rely on the existence of nightvision, I am not going to remove them or change them based on a balance decision TG made

**Comment by TetrakoHateThis** [comment]
Didn't take Goof long to lay their thoughts down. 
Due to the diversity of alien species we have here, night vision is one of those few mechanically positive quirks we have that actually serves a purpose beyond the constant rampant powergaming that must occur at /tg/, emphasizing characters that might have an acclimation for darkness and allowing a player to facilitate that both mechanically and ICly. Removing this on the frankly flimsy premise of stealth antags/nightmares being super reliant on vantablack darkness simply can't fly here.

**Comment by Hemlock32** [comment]
Yeahhh uh
Night vision here has been completely reworked to essentially function completely differently here including colour tints and, additional synergy with hypersensitive, and, various levels of night vision as well

Not to mention darkness itself also functioning differently

**Comment by Iamgoofball** [comment]
Oh if you guys fixed the night vision issues laid out in the PR then aight based

**Pull request merged**
