### PR TITLE
Explodes The Simple Farm Component And Some Related Features; Adds Turf Farming Except If It Wasn't Mid

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

The old simple farming component that jake added on skyrat has been exploded.
Some things that really didn't need to exist have been removed, like planting in minecarts, or the free nitrogen generator plant tanks.

All of this has been replaced with the new (cooler) turf farming component. Seeds can be used on any turfs that were farmable before, except now instead of just spawning a structure that looked like plants and spawned free crops every like five minutes, it now spawns a "farmable land" and plants the seed in it.

This farmable lands behaves like a hydroponics tray with autogrow enabled, but also still allows plant mutations to happen at high instabilities.
## How This Contributes To The Nova Sector Roleplay Experience

The simple farming component was not good. It created structures that generated free plants at a significantly higher rate than just growing the plants would, and allowed upgrades to make enough food to feed the entire server seven times over every five minutes. Aside from that however, the system was also really janky and like with all past jake features, not very intuitive for people to use compared to it's on-station counterparts.

Which extends to the plant tank, which you could make anywhere for some garden mulch and a toothpick to create ungodly amounts of nitrogen while also growing the aforementioned bazillion plants.

This keeps the original idea of low-maintenance farming for the primitive roles, while also working more similar to actual hydroponics and keeping all of the fun interactions that have been developed for that.
## Proof of Testing
image

## Changelog
:cl:
add: A new turf farming component has been added, which replaces old simple farming for allowing low-maintenance crop growing for primitive roles.
del: The old simple farming component has been deleted, alongside the plant tank and the ability to plant crops inside of minecarts
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
The plots counting as being on autogrow make this a lot less daunting than I initially assumed it'd be, having been a Hearthkin gardener myself a good few times. I think it'll go over fine, especially with how powerful the basics like ez nutrient still are in this day and age.

**Comment by Nerev4r** [comment]
Planting in minecarts had soul tho ngl.

**Comment by GoldenAlpharex** [comment]
How do primitive ghost roles use this, considering they won't have an easy access to making nutrients to fuel these?

**Comment by Paxilmaniac** [comment]
> How do primitive ghost roles use this, considering they won't have an easy access to making nutrients to fuel these?

You don't need to get nutrients or water. They get free self sustaining.

**Comment by GypsumKobold** [comment]
Can they cross pollinate? Autogrow doesn't usually forgo nutrient requirements, is this a change specific for these to not require nutrients? You said they can mutate with instability, so even if they don't *need* nutrients can Left 4 Zed still be used?

Worm barrels can allow access to the basic botany chems however they also likely assumed the massive amounts of product simple farming used, I'm unsure how many units worm fertilizer grinds into and may require balancing.

**Comment by GypsumKobold** [comment]
Something pointed out, the nitrogen trays make for really nice decorations. Instead of removing them wholesale can we make them non functional? Doesn't produce nitrogen, the plant planted 'grows' but you can't harvest it. Digging the plant out of the try just refunds the seed you planted.

**Comment by OrbisAnima** [comment]
> > How do primitive ghost roles use this, considering they won't have an easy access to making nutrients to fuel these?
> 
> You don't need to get nutrients or water. They get free self sustaining.

this is a big balance problem I feel, and the sensation I get from these is that they were made with the intention to tribals  oriented to hydro cross polinization gaming, without the energy issues or even the new tray problems we usually have on station, which bears the question why arent earth mounds enough?

First off, they have a base of 30 nutriments per tray, while the regular tray get 20, there are certain nutriments that work per 10 nutriment in the tray, a big example being Left 4 zed, for faster increase of instability.

Second, self substaining removes weeds, pests and adjust water, it has nothing to do with nutriments, you do get nutriments from  grinding worm food though.  What Self substaining let you do is prevent mutations and thus roll the dice on chems, letting you get specialty chems that wouldn't be easy or possible to get.

Third, I dont see how magical t2 bins and theorically t4 free trays wouldn't result in the same issue you mentioned of people having loads and loads of crops, if anything, it feels like a hidden buff attempt to get people to be better at hydro than hydro, we already got that with cargo being able to produce trays before hydro can.

Lastly, the sprites dont coincide, you use lines of three for things that were imagined for a single line, it would be wise to adapt to that, as even the plants in the example look off.

**Comment by Thlumyn** [comment]
Overall, this just feels removing what makes turf farming unique and making them just better hydroponics trays. 
Sure, primitive farming was easy and produced quickly, but the drawback was that you couldn't do things like grafting, cross-pollination, and instability farming - but mostly that they only dropped a couple crops with low potency. With the ability to increase yield and potency through nutrients, I think this has the potential to make it faster to grow large quantities than the old turfs. It just feels weird to restrict something that is better for the job to turfs that are (usually) off-station; as it is with this, I don't see any reason for the botanist to not just pack up and move down to lavaland and do everything with turf farming. It also makes it harder to mutate plants which was one of the few nice advantages of turf farming - trying to figure out how to increase stability to get the steelcaps or meatwheat that I would previously get quickly while farming as an icecat does not sound particularly fun. 

The sprites are really cute though, especially the horizontal ones

**Comment by GoldenAlpharex** [comment]
Echoing the thoughts of many others, I think this kind of makes the simple farming into a far more complex system than it had to be, and while yes you could have a lot of produce, they were all low potency ones, which means that you'd have to do some real planting if you wanted to have something more solid. Not only that, but these require less supervision, which is a good thing when you're a primitive ghost role that has to tend to many other things. The chance to yield mutated crops was also low enough that it would actually take a long time in many cases to get the mutation you want, because you keep on having to do many other things at once, so this ends up only really being profitable if you're constantly actively monitoring the plants, and it's still low potency plants regardless.

**Comment by Paxilmaniac** [comment]
Yeah. Lemme just rewrite the entirety of hydroponics code upstream real quick. (no)

**Comment by Paxilmaniac** [comment]
I don't care about jake code enough to spend any time doing allat, it'll just have to stay mid for a while longer.

**Pull request closed without merging**
