### PR TITLE
Hearthkin translator

### PR DESCRIPTION
**Pull request by Thlumyn**
## About The Pull Request

Adds a sprite, equip text and map location for the Hearthkin translator; which works like the ashwalker necklace but gives the wearer Siik'tajr. 
## How This Contributes To The Nova Sector Roleplay Experience

The hearthkin translator was added in a previous PR but not included yet as it didn't have its own sprite and stuff. 
This should make it easier to have a last ditch solution to talking with outworlders.
## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
image
image
image
image

</details>

## Changelog
:cl: GoldenAlpharex for the code, Thlumyn for the sprites & mapping
add: Added translator room to the Hearth map.
image: Added a unique sprite for the Icecat's translator
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — APPROVED** [review]
Sprites look good to me, I can't really review the code since it's my own though.

**Review by Zergspower — CHANGES_REQUESTED** [review]
Given this affects the ashwalker necklace as well please test that.

**Comment by Thlumyn** [comment]
I did test it with ashwalker necklaces as well; I can get screenshots in a bit

**Comment by Thlumyn** [comment]
image
 @Zergspower

**Comment by ApplePlastic** [comment]
I'd honestly rather it be the trading language rather than the sacred language, considering the language is Supposed To Be Sacred And Only Used By Hearthkin.

Just my two cents, though.

**Comment by Thlumyn** [comment]
> I'd honestly rather it be the trading language rather than the sacred language, considering the language is Supposed To Be Sacred And Only Used By Hearthkin.
> 
> Just my two cents, though.

It is the trading language

**Comment by Zergspower** [comment]
> image @Zergspower

alrighty - we had some weird behavior when unequipping it when i did the last PR for it, it wasnt removing the language at first even though it was supposed to lol

**Review by Zergspower — APPROVED** [review]

**Comment by ApplePlastic** [comment]
> but gives the wearer Siik'tajr

i 4got which was which my bad

**Pull request merged**
