### PR TITLE
Adds a cool dorsal frill to markings for lizards

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title. Sprite provided by thgvr. 

## How This Contributes To The Skyrat Roleplay Experience

its cool

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image

image

</details>

## Changelog

:cl:
add: Adds a cool dorsal frill in head markings
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
will address previously reviews later

**Comment by thegrb93** [comment]
Couldn't this be done on TG?

**Comment by GoldenAlpharex** [comment]
> will address previously reviews later

What were those, and are you still planning on addressing them?

**Comment by nikothedude** [comment]
oh i completely forgot about this pr, whoops
if i ever get the drive to make this, ill reopen

**Pull request closed without merging**
