### PR TITLE
Portal storm with lavaland mobs

### PR DESCRIPTION
**Pull request by honkpocket**
## About The Pull Request

Did you know the Necropolis hates us?

## How This Contributes To The Nova Sector Roleplay Experience

Regular station dwellers should face these creeeeetures more often.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  

https://github.com/user-attachments/assets/3ddc3d94-306d-4919-8e9e-0f25a2f0e27e

</details>

## Changelog
:cl:
add: Portal storm event which spawns most lavaland monsters
/:cl:

Hey you, before you hit that emoji reaction, consider actually commenting instead; it'll be 1000x more useful, thank you!

### CODE REVIEW

**Comment by honkpocket** [comment]
Would love to hear some voices instead of up and down doots, particularly for this PR. I made it while feeling a bit silly and I'm still uncertain if its a Good or Bad idea, emojis aren't going to help me much.

**Comment by Zergspower** [comment]
Still chewing on it, shared concern is goliaths and legion on station, where one is armored against what the station's usually armored against and the other has a moderate chance to spiral

**Comment by Zergspower** [comment]
> Would love to hear some voices instead of up and down doots, particularly for this PR. I made it while feeling a bit silly and I'm still uncertain if its a Good or Bad idea, emojis aren't going to help me much.

i did just realize something, nothing really says we cant include all mobs. Given Goliaths are my primary concern on it, let's see what it feels like with swapping them with the gutlunch instead?

**Comment by honkpocket** [comment]
Do Gutlunches do anything? I'm not very familiar with 'em. What if I remove all the goliaths, and add 1 ancient one to the boss_type listings? Or maybe just 1 normal goli as boss_type?

**Comment by TetrakoHateThis** [comment]
> let's see what it feels like with swapping them with the gutlunch instead?

Last I remember, the Ashwalker bugs weren't hostile or threatening even slightly. Also, crew do have a couple means to fight against mining mobs, given we have Hunter shotgun slugs plus, you could always add the Nemesis component to things like Reagent Weapons/Normal arrows to balance that out further. Add that to the fact that Lavaland fauna is designed to only be a remote threat to a single target and station crew generally rally against portal storm threats pretty quickly, so a single goliath is going to be no more or less threatening than a Stormtrooper or pistol-having Shocktrooper.

**Comment by Zergspower** [comment]
> Do Gutlunches do anything? I'm not very familiar with 'em. What if I remove all the goliaths, and add 1 ancient one to the boss_type listings? Or maybe just 1 normal goli as boss_type?

1 ancient works for me instead

**Comment by HoodMilk** [comment]
You could spawn the baby goliaths from the broodmother fight instead of full goliaths.

**Pull request closed without merging**
