### PR TITLE
Unapologetic TTS Nerfs Vol. 1

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
Basically this just replaces the 'Hello, this is my voice' with something more useful. Like how the borg one is objectively more useful.

This also lowers max pitch to +4 and min pitch to -8.
## How This Contributes To The Nova Sector Roleplay Experience
The higher voices are comically shrill especially with the Persona TTS voices, and there's genuinely no situation in which +12 is desirable.

## Proof of Testing
I fucking can't, so you'll probably have to TM this.

## Changelog
:cl:
sound: Max and minimum pitch for TTS have been adjusted, and the test line is now longer.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
hi, I chose +12/-12 as that's up/down an octave in the code for the voice changer part of the TTS stack, I really don't recommend changing it

you should also replace the test text with an input box or something instead

**Comment by Hemlock32** [comment]
My character's voice isn't even high pitched and I use +4 to achieve that
There are some small characters with extremely high pitched voices that would be jarring to hear at the same barely higher pitch that my character's voice is at

**Comment by Iamgoofball** [comment]
I'm looking into this from the TTS end of things, will post an update here once I've got one

**Comment by Hemlock32** [comment]
> I'm looking into this from the TTS end of things, will post an update here once I've got one

Curious what that will entail
Hopefully fixing some, weird mispronunciations?
Ex. "Hm" "Mhm" "Xenobio" "Bandana"

**Pull request closed without merging**
