### PR TITLE
Removes the permit check for secbots being default

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

Beepsky doesnt understand what permits are for and in turn think anything with certain flags are just weapons, until a more elegant solution is presented we're just going to undo the modular edit. I like the idea of it don't get me wrong, but it's too broad of a stroke and catches too many innocent items in the way which leads to people just breaking sexbots on sight because they're trying to do their job.

Botanist buff: You can now use your job tools without beepsky trying to beepsky you.

## How This Contributes To The Nova Sector Roleplay Experience

I and many people are kind of tired of getting baton'd by beepsky for having general job tools. Floral ray from botany for example or even a skateboard. 

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>

Kinda hard to prove this but since it's a modular edit removal i'll just show the compile.
  
image

</details>

## Changelog
:cl:
balance: Undoes the permit flah for Beepsky, normal job tools shouldnt make them angry anymore.
/:cl:

### CODE REVIEW

**Comment by TripleShades** [comment]
> breaking sexbots on sight

**Comment by PowerfulAtom111** [comment]
i think this removes one of the main uses of beepsky, and that the "more elegant solution" should be worked on and merged instead of this because I can already see this never getting that solution

**Comment by Zergspower** [comment]
> i think this removes one of the main uses of beepsky, and that the "more elegant solution" should be worked on and merged instead of this because I can already see this never getting that solution

this doesnt remove the ability to toggle, this removes the roundstart permit check

**Comment by Zergspower** [comment]
> #3002 let me know if there are more items that have the flag.

Thanks - will try to find any outliers

**Pull request closed without merging**
