### PR TITLE
cow

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

adds cow

295907696-aa0985d8-cd43-48f9-8293-6db39f85f84a

295907746-2319abdf-9831-421a-81ee-8942cccbbc9c

## How This Contributes To The Nova Sector Roleplay Experience

adds cow

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog
:cl: tf4, orion
add: Added cow print underwear.
/:cl:

### CODE REVIEW

**Comment by HoodMilk** [comment]
cow

**Comment by Paxilmaniac** [comment]
🤨

**Comment by OrionTheFox** [comment]
What a disaster.

**Comment by Iamgoofball** [comment]
upstream this

**Pull request merged**
