### PR TITLE
Mlem Time (adds new nose licking animations)

### PR DESCRIPTION
**Pull request by Jinshee**
## About The Pull Request

Adds 2 new facial hair options, both animated.

## How This Contributes To The Nova Sector Roleplay Experience

https://github.com/user-attachments/assets/e6509008-cbd5-4701-837d-c38c6ba8ff3e

## Proof of Testing

https://github.com/user-attachments/assets/c75c39b9-d7df-4d2b-8d70-abcdb189171b

https://github.com/user-attachments/assets/d26ee6c3-1c03-4b9a-a28f-133abb07d928

and one of our more absurd snouts: elephant! for fun

## Changelog

:cl:
add: Two new animated facial hair options: Snake Lick and Nose Lick
/:cl:

### CODE REVIEW

**Comment by Jinshee** [comment]
yes, you can cut off someone's tongue with a razor now

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I feel like this would probably fit better as an/multiple emotes, rather than something that's always on via facial hair. That way, people could toggle it on and off, and I definitely see people wanting to just do something like *licklips to lick their lips like that as a one-off thing, rather than a permanent part of their sprite/character. The tongue sprite used could then simply be based on the tongue the character has.

**Comment by GoldenAlpharex** [comment]
Otherwise, the sprites look fine to me.

**Comment by Jinshee** [comment]
image_2024-07-25_143816275

**Comment by CliffracerX** [comment]
I would suggest including some support for a middle-ground - either an emote or some other customization option that lets you keep a persistent flicking tongue for snake/lizard characters.

**Comment by Jinshee** [comment]
i will not end up doing the changes requested, but someone else offered to if they'd ever like to get around to it. till then

**Pull request closed without merging**
