### PR TITLE
Goon alt titles

### PR DESCRIPTION
**Pull request by Aether217**
## About The Pull Request

Adds goon titles for department guards and an additional Lab Guard alt title to the science guard because I got a random dash of inspiration.

## How This Contributes To The Nova Sector Roleplay Experience

The definition of goon really fits the theme of dep guards, as they are violent and brutish individuals that generally respond to the head of the department as their loyal defender.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog
:cl:
add: Goon alt titles to dep guards
add: Lab Guard title to science guard
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I don't like this, mainly because "Goon" feels too informal and demeaning to be an actual job title.

**Comment by Iamgoofball** [comment]
GNuZIskXUAAmFST

**Comment by Aether217** [comment]
> I don't like this, mainly because "Goon" feels too informal and demeaning to be an actual job title.

I can see what you mean but Goon has had a resurgence on the Internet and it's more synonymous with the "tough but a tad goofy" enforcer than it's old meaning. 

As for the demeaning part, it's something that the player would have to actively select so only the people who would have no issues with being called a goon would have it as their title.

**Comment by Aether217** [comment]
That said, if it they just don't fit in I'll open a different PR for the Lab/Laboratory Guard and maybe cook a few more alt titles in a more serious theme to justify it.

**Review by Aether217 — COMMENTED** [review]
ok

**Comment by GoldenAlpharex** [comment]
> That said, if it they just don't fit in I'll open a different PR for the Lab/Laboratory Guard and maybe cook a few more alt titles in a more serious theme to justify it.

Yeah, I think this would be preferrable.

**Pull request closed without merging**
