### PR TITLE
Adds four new hairstyles

### PR DESCRIPTION
**Pull request by Draggeru**
## About The Pull Request

This PR adds four new hairstyles: Royal Curls, Elegant Bun, Mermaid, and Thick Ponytail

## How This Contributes To The Nova Sector Roleplay Experience

Four new unique hairstyles to further empower the illusion of free choice. (You WILL pick the new hairstyles OoOOoooOOo)

## Proof of Testing

Game complies

haiiirrr

Screenshot is mobs spawned in game with a black tile background

## Changelog

:cl:
add: Adds four new hairstyles: Mermaid, Thick Ponytail, Elegant Bun, and Royal Curls
/:cl:

### CODE REVIEW

**Comment by Draggeru** [comment]
Running checks and grabbing screenshots

**Comment by Draggeru** [comment]
Update: Im stupid

**Comment by Draggeru** [comment]
Ready for review

**Review by GoldenAlpharex — APPROVED** [review]
These all look great, as expected, coming from you! 😎

**Pull request merged**
