### PR TITLE
[MIRROR] Add: 2 Quirks Configs

### PR DESCRIPTION
**Pull request by NovaBot13**
Original PR: https://github.com/tgstation/tgstation/pull/81033
-----
## About The Pull Request

This PR adds two new config options for quirks:
- *Flag* `DISABLE_QUIRK_POINTS`
  - When enabled, disables quirk points balancing.
  - When enabled, players can select positive quirks without first selecting negative ones.
  - When enabled, the quirk points balance visually hides itself on the Quirks page.
- *Number* `MAX_POSITIVE_QUIRKS`
  - Limits the maximum quantity of positive quirks which players can select using the Character Preferences page.
  - I ported this from the old `MAX_QUIRKS` define.
  - When set to `0`, players won't be able to select any positive quirks, and they won't appear on the Quirks page.
  - When set to `-1`, players will be able to select any quantity of positive quirks.
  - When commented-out or undefined, the default is `6`.
  - When set to `0` or `-1`, the positive quirk balance visually hides itself on the Quirks page.

## Why It's Good For The Game

There is some downstream repositories asking for the quirks system to be configurable. Additionally, I always find myself tweaking these values on my own private servers and I thought it would be nice to share my edits. Usually I was simply commenting-out sections of this code in order to get the same result, so it helps to have an official way to disable quirk points.

## Changelog

:cl: A.C.M.O.
config: Added two new config flags for quirks, DISABLE_QUIRK_POINTS and MAX_POSITIVE_QUIRKS.
/:cl:

### CODE REVIEW

**Comment by Floofies** [comment]
I will make some edits to our Augments+ code to make `DISABLE_QUIRK_POINTS` work.

**Comment by Floofies** [comment]
Working on [upstream-hotfix-81033](https://github.com/Floofies/NovaSector/tree/upstream-hotfix-81033) to make this mergeable

**Comment by SomeRandomOwl** [comment]
needs to wait for @GoldenAlpharex

**Review by GoldenAlpharex — APPROVED** [review]
Been test-merged, works fine, let's get this 🍞

**Pull request merged**
