### PR TITLE
SC-1 and SC-2 are `normal` w_class

### PR DESCRIPTION
**Pull request by carpotoxin**
## About The Pull Request

Revival of https://github.com/NovaSector/NovaSector/pull/450.

## How This Contributes To The Nova Sector Roleplay Experience

Puts these guns on the map, and honestly deserve another buff like cell capacity.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 Maybe if I actually tweak them significantly.
</details>

## Changelog
:cl:
balance: Allstar SC-1, Allstar SC-2, Adv E-gun, Laser carbine, Laser musket, Retro laser, Laser shotgun are now `normal` weight-class.
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
> Puts these guns on the map, and honestly deserve another buff like cell capacity.

Could you please explain in more detail how this contributes to the NovaSector roleplay experience? It isn't very obvious from the wording you have given.

**Comment by honkpocket** [comment]
The guns are bad compared to the competitors in every fathomable way.

**Review by Sadboysuss — COMMENTED** [review]
the sprite doesn't make it very intuitive to carry them in your bag, neither do players from other codebases where this gun is bulky will intuitively understand that it's normal sized,
I think a better solution would be to increase their energy capacity or damage.
I also think it's very goofy to carry 5 energy guns in your bag, the reason guns were made bulky was that people could carry whole armories in their bag.

**Comment by honkpocket** [comment]
> the sprite doesn't make it very intuitive to carry them in your bag, neither do players from other codebases where this gun is bulky will intuitively understand that it's normal sized

I'm not here for this kind of balance discussion.

> I also think it's very goofy to carry 5 energy guns in your bag,

Rulebreak, players are not allowed to carry that many guns.



In brief: Refer to the previous PR for statements on balancing.

**Comment by SomeRandomOwl** [comment]
> > the sprite doesn't make it very intuitive to carry them in your bag, neither do players from other codebases where this gun is bulky will intuitively understand that it's normal sized
> 
> I'm not available for this kind of balance discussion.
> 
> > I also think it's very goofy to carry 5 energy guns in your bag,
> 
> Rulebreak, players are not allowed to carry that many guns.
> 
> In brief: Refer to the previous PR for statements on balancing.

it is a rulebreak but we shouldent enable people to have an easier time to break rules, sometimes people just do it accidentally without realizing it, if we make it easier to have more guns on your person people will just inherently accidentally break the rule

**Comment by lessthnthree** [comment]
Why not buff the gun itself, not make it into a weak rifle that magically fits in a satchel?

**Comment by honkpocket** [comment]
> Why not buff the gun itself, instead of making it into a weak rifle that magically fits in a satchel?

The hoshi already fits in the backpack and is currently the dominant lasergun. I'll buff the gun, but not in this PR, this is just meant to be a w_class thing.

**Comment by RatFromTheJungle** [comment]
> This affects all the subtypes of `/obj/item/gun/energy/e_gun` and `/obj/item/gun/energy/laser` (except the x-ray laser gun which you've overridden to be bulky again) so you should make that clearer in the title and body.
> 
> Not hugely a fan of this approach to be honest (both from a maintainer perspective and just general gameplay perspective).

there's functionally no reason to keep them bulky sized, they're already worse then all the competitors, and very likely always will be because of the inaccessibility most departments have to weapon rechargers, the disabler SMG is already a leagues better non-lethal compared to them, and fits in your bag already, and for lethals:
literally any other choice is better, down the list, any of them

**Comment by honkpocket** [comment]
> This affects all the subtypes of `/obj/item/gun/energy/e_gun` and `/obj/item/gun/energy/laser`
Updated the CL accordingly.

**Comment by Sadboysuss** [comment]
If you want to make the energy gun normal so bad and don't want to do the Sprite adjustments, then replace all its instances with the miniature energy gun and buff it. Please at least put that much effort into your balancing.

**Comment by honkpocket** [comment]
I would love to give them a sprite overhaul and a slap on the butt so they shoot better, but I have a sprite project backlog. I've commented it before, its out of scope for this PR; and so is replacing all Xs with Ys.
Whatever happens to this PR, closed or merged, _anyone_ could do that sprite overhaul afterward.

**Comment by RatFromTheJungle** [comment]
> > The hoshi already fits in the backpack and is currently the dominant lasergun. I'll buff the gun, but that's out of scope for this PR.

>That...honestly is not something that should be `W_CLASS_NORMAL` to begin with. That must have slipped by us, urgh.

The hoshi is the pistol variant of the 'Hyeseong', that is, it's the smaller (energy-gun) version, wherein the 'Hyeseong' is buffed to be befitting of it's bulky status and actually looks like a *rifle*, wherein making the hoshi also bulkysized would make it almost-literally a useless pick, because the rifle already does everything it does, better. 
which will come back like the black-plague in a follow-up: 
> From a balance perspective perhaps (given the current state of these weapons)? But as someone else mentioned the solution there is to buff the guns if they are not meeting expectations for a bulkier rifle-type of weapon. Things that fit in your backpack should be limited to smaller sidearms and such, it makes no sense to be able to just pack a rifle or two in there.

The fun starts here: When you would think of ways to 'buff them' you have to overlook what they already look like, which is glorified pistols, which is also counter-intuitive to the point below this 
image
which, if the image showing them being one-handed doesn't show well-enough, they're intended to be pistol sized(as compared to the mosin in the middle), you'd have to bend the definition pretty far to see them as 'rifle'
> It should be unambiguous. "The sprite shows a bulky rifle, yes of course that's not going to be able to fit in a backpack". Otherwise you get people arguing "well this gun fits in the bag and is better than x or y"! and then it gets silly pretty fast.
> 
> So: ideally it should make sense, be consistent, and there should be a benefit for being not able to carry a gun in your bag (e.g. larger magazine capacity, more power, etc). If any of the current lineup guns is failing in that expectation (like the Hoshi for example being able to fit into the bag while being a rifle, or the normal energy rifles being underpowered) then I think it all needs to be looked at and tweaked a bit for consistency.
> 
> Ultimately by muddying the waters further when it comes to gun `w_class` I think this might actually make matters worse in the long run, which is partly why I'm against it.
> 
> (as a sidenote...I remember the days when they _could_ fit in your backpacks, people would just load up on energy guns and carry around an armory in their bags. I really don't want to be bringing us back to there.)

and, to tie this back around to the latter half of this, as I think the above point fills out the majority of the argument for the first half:
there is nothing stopping you from buying like 6 shotguns, sawing them off, and cramming them all into a sec belt, or 6 of whichever pistol, and having more immediate and varied firepower available, (or the GOAT, backpack of sawn off mosins) and it's still functionally never done, because most people realize it's not only powergaming, but entirely pointless to do (there is almost never a fight where having more then 2 guns will come into play, with most fights being like, 20-30s at **max**) which, you could presently do with the Hoshi, and that, equally, is rarely if ever done. So I don't think there's much fear of everyone suddenly running around with a bunch of eguns in their bag, especially when there's already **better** (and sometimes, easier to get) options available all around them, making them normal sized just makes them slightly more appealing in instances where it befits the character, or for roles that get one by default (like the HOP/HOS) without a real risk of it suddenly becoming the new trend to rush them.


With an honorable mention to 'most of the buffs you **could** do to make them 'bulky befitting' would just turn them into the  'Hyeseong' (automatic disabler, burst fire laser, self charging, pretty big capacity)

**Comment by Sadboysuss** [comment]
Sounds like a lot of balance problems that should be addressed then. This isn't just energy guns being bad. It's everything else being overwhelmingly much better

**Comment by RatFromTheJungle** [comment]
> Sounds like a lot of balance problems that should be addressed then. This isn't just energy guns being bad. It's everything else being overwhelmingly much better

fortunately, nothing else is really 'stand out powerful' outside of the GOAT of the aeon (the mosin, again), it's much closer to 'e-guns have been abandonware for four years of balance changes here, because everytime someone had changed something about them, people who didn't understand the overall balance as well as they could would argue endlessly about the implications'

**Comment by RatFromTheJungle** [comment]
> Those do not look like pistols to me. Just because something can be held in one hand does not mean it is 'pistol-sized' and able to be shoved into a backpack.

please don't make me comment on this, you would not like the answer for what makes something a handgun
> If you just look at the code it is also pretty unambiguous to me that the regular energy gun is supposed to be _big_.

They were actually, originally, backpack sized, which the mini-energy gun (mentioned later) was pocket-sized (continued at the end of post)

> https://github.com/NovaSector/NovaSector/blob/68c5c7e67bbe540351c59a25dc135334a6e22cc5/code/modules/projectiles/guns/energy/energy_gun.dm#L1-L3
> 
> https://github.com/NovaSector/NovaSector/blob/68c5c7e67bbe540351c59a25dc135334a6e22cc5/code/modules/projectiles/guns/energy/energy_gun.dm#L31-L34
> 
> > and, to tie this back around to the latter half of this, as I think the above point fills out the majority of the argument for the first half: there is nothing stopping you from buying like 6 shotguns, sawing them off, and cramming them all into a sec belt
> 
> That is something that is solvable relatively easily, and I believe there are already examples in the code of limiting storage to one type of a particular item (usually guns).

this implies it's seen as an issue, or presents itself as such, which the -

> > it's still functionally never done, because most people realize it's not only powergaming, but entirely pointless to do (there is almost never a fight where having more then 2 guns will come into play, with most fights being like, 20-30s at **max**) which, you could presently do with the Hoshi, and that, equally, is rarely if ever done.
> 
> I'm just a little confused here. If it is not an issue, and basically never done, then how does making them normal sized solve _any_ of the issues with them being underpowered?

 above comment doesn't realize, it doesn't fix them from being 'underpowered,' it makes them more portable(see: convienent), instead of requiring the beltslot (used for alot of jobs) or you to get an armor-vest to put it on the armor-slot, the present situation doesn't do a whole lot but double-punish you for deciding to /not/ use a ballistic, or the hoshi
> > With an honorable mention to 'most of the buffs you **could** do to make them 'bulky befitting' would just turn them into the 'Hyeseong' (automatic disabler, burst fire laser, self charging, pretty big capacity)
> 
> As opposed to turning them all into pistols?

Thankfully, they're in their present form, the prime example of 'pistol balance,' worse then everything that's bulky, but it fits in your bag 
> Ultimately this PR fails the 'why is it good for the game' for me. I just don't see it as the right direction for this particular issue, or how it helps at all.
> 
> edit: to elaborate on this, so you don't feel like I am just singling you out here:

(i don't really care, even if you were)
>     1. This is a lazy change that arguably does not address the core issue. I'm giving it the same treatment I would any other pr that attempts that. I would like to see an actual effort on balance rather than this!

A change without alot of fundamental changes to the items to move their position in the balance tree, sure, but lazy isn't really the best way to describe it, because energy guns are already firmly in a widescale balance of 'kinda ass, but better then a toolbox' which is the ideal situation for something that fits in your backpack, 

>     2. It changes the energy gun basetype (which upstream are considered bulky). This has implications for maintenance, especially concerning additions of new guns and potential buffs that come from upstream in the future.

Which, I'll tie back to the above-comment on their original size, upstream changed them to bulky because they were scared of people roaming around with 6 of them in their backpack, doing absolutely nothing but validhunting, which is a situation we don't particularly have to worry about with the availability of guns that fit in your backpack anyway, and the near-criminal lack of people running around with 6 wespes, or 6 bobrs, or w/e in their bag. 

Very likely, because not only do we not have as many people deadset on doing absolutely nothing but validhunting, but we also don't really share TG's 'crew balance,' that is, we don't have a focus on keeping people towards improvised or elsewise tools-doubling-as-weapons, which is why energy guns being normal sized would do nothing but just bring them into line with everything else in the suggested 'fits in your backpack' weightclass

**Comment by gamermomentum** [comment]
Me when I can hold 7(seven) SMGs in my bag with the potential to turn 4 spacemen sideways each, and cause debilitating bleeds with each burst, I can then hold 6 additional whole mags(For a bonus 24 sideways spacemen) in my pockets for a grand total of 52 sideways spacemen in 1 inventory.
Of course that doesn't happen 'cause rule 8, so laser guns being backpackable(And being concealable, like the drastically better ballistics) isn't really some catastrophic line being crossed into powergaming. 

And the gunns aren't even really "op". Taking 6 shots(You can't shoot someone 5 and then .4 of a time(s) after all) to down unarmoured guys is a pretty good balance of "guns being threatening enough to be dangerous IC" w/o just being overwhelming.

**Comment by projectkepler-ru** [comment]
> Me when I can hold 7(seven) SMGs in my bag with the potential to turn 4 spacemen sideways each, and cause debilitating bleeds with each burst, I can then hold 6 additional whole mags(For a bonus 24 sideways spacemen) in my pockets for a grand total of 52 sideways spacemen in 1 inventory. Of course that doesn't happen 'cause rule 8, so laser guns being backpackable(And being concealable for permit reasons, like the drastically better ballistics) isn't really some catastrophic line being crossed into powergaming.
> 
> And the gunns aren't even really "op". Taking 6 shots(You can't shoot someone 5 and then .4 of a time(s) after all) to down unarmoured guys is a pretty good balance of "guns being threatening enough to be dangerous IC" w/o just being overwhelming.

don't guncase still exis? I havent been playing in the past 9 months but if so then you can put 4 into them and you can put 7 guncase so that's 21 e-gun or laser gun

**Comment by projectkepler-ru** [comment]
> This affects all the subtypes of `/obj/item/gun/energy/e_gun` and `/obj/item/gun/energy/laser` (except the x-ray laser gun which you've overridden to be bulky again) so you should make that clearer in the title and body.
> 
> Not hugely a fan of this approach to be honest (both from a maintainer perspective and just general gameplay perspective).

query
if these gun are so bad because they are utterly outclassed by competition
would it not be wise to see why the others are better?

**Comment by gamermomentum** [comment]
> query if these gun are so bad because they are utterly outclassed by competition would it not be wise to see why the others are better?

The others are better 'cause detachable magazines, and bleeding wounds/brute damage blows out burn wounds/burn damage. They don't actually have obscene numbers. They're pretty much the baseline of combat. 
SC-1 and SC-2 aren't even in station armouries. Afaik they've been replaced with Hoshis and Sindano kits respectively.
They're just bad guns you can order from cargo with like half the ammo of their ballistic counterparts. 

>don't guncase still exis? I havent been playing in the past 9 months but if so then you can put 4 into them and you can put 7 guncase so that's 21 e-gun or laser gun

You're right. You could actually have like 28 SMGs in your bag(Because you can carry like 4 in a guncase) and 2(?) in your belt if you use a holster/secwebbing for a total of 30 SMGs and like ~120 potentially dead guys. 

Once again, though, nobody plays like this because some ghost/admin would pretty much immediately go "Why does this guy have 30 guns. He's powergaming??" and they'd get owned. 

You could make an argument for Advanced Eguns being a line to draw about this but actual regular Eguns and laser rifles really just kinda blow rn and don't need to be so restricted compared to basically every other gun in the game.

**Comment by RatFromTheJungle** [comment]
> > above comment doesn't realize, it doesn't fix them from being 'underpowered,' it makes them more portable(see: convienent),
> 
> I do realize and am aware of the issue. As for the 'convenience' argument, that is not compelling enough for me given we are making the mini egun obsolete in the process.
> 
> All I'm hearing repeatedly is 'energy guns are bad right now compared to everything else' but this PR does not do anything to address the underlying issues with them.
> 
> Ultimately it is a half measure and fails the 'Why is it good for the game' justification. So like I would for any other PR that tries an unsatisfactory measure I would ask we please attempt to find an alternative solution to 'put these guns on the map' again. Which is something I am all for doing, just with a little bit more effort behind it...
> 
> Until then, sorry but no.

the mini-egun fits in normal boxes, and your pocket, so that's still an inaccurate claim, but i've talked with golden and settled on 'we're better off just removing energy guns, because presently, they're worse-off versions of the hoshi' which is certainly another way to do it

**Pull request closed without merging**
