### PR TITLE
Add Shorg (New dog subtype)

### PR DESCRIPTION
**Pull request by Microvolnovka19**
## About The Pull Request
Some time ago I saw a cool gif of a shark with legs and decided to add it:

image

## How This Contributes To The Nova Sector Roleplay Experience

More variety to the mob pool is good

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image
image
image
image
image

</details>

## Changelog

:cl: SuperDrish
add: Added new ultra duper giga hyper SECRET cool mob - shorg. You totally can not order it in cargo.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
isn't that shork (shore shark)

**Comment by Microvolnovka19** [comment]
> isn't that shork (shore shark)

I have no idea. The only source I had is a gif

**Comment by Stalkeros2** [comment]
me neither

**Comment by DevillishOne** [comment]
https://youtu.be/2vVQYdG0YlU?si=GE2JsMo-l8MXuZXS

SHARKS WITH LEGS

**Comment by Hlscientist** [comment]
https://www.youtube.com/watch?v=2vVQYdG0YlU

**Pull request merged**
