### PR TITLE
Science advanced tools are faster

### PR DESCRIPTION
**Pull request by delingar**
## About The Pull Request

Science advanced tools get 0.5 toolspeed (0.7 engineering).

## How This Contributes To The Nova Sector Roleplay Experience

Science adv tools are just nerfed engi tools. They MUST have their positive sides when compared with engi version

## Proof of Testing
[Video](https://youtu.be/IX0Z2gGRKFk)

## Changelog
:cl:
balance: Science advanced tools are a bit faster then engineering
/:cl:

### CODE REVIEW

**Comment by 1393F** [comment]
I don't get it, why should they be better than engineering tools? When constructing isn't even science's job compared to engineering? Currently they(from what I've read) are in no way nerfed from engitools, they just have a different sprite, they're even unlocked in the same research node? Why should science get better tools than engineering for doing engineer's jobs?

**Comment by delingar** [comment]
> I don't get it, why should they be better than engineering tools? When constructing isn't even science's job compared to engineering? Currently they(from what I've read) aren't really nerfed tools besides the jaws being unable to pry doors, they just have a different sprite, they're even unlocked in the same research node? Why should science get better tools than engineering for constructing things?

Main reason why they are faster is synth surgery. They are faster at surgery because they are... Made for more delicate job? Their construction speed is faster because that's code issue, that surgery steps have no code for list of tools and their workspeed and i don't really know how to code it

**Comment by Iamgoofball** [comment]
science powercreep lmfao

**Comment by nikothedude** [comment]
why are you buffing the drill? it is already on par with the engi drill and that is a buff for no reason

**Comment by nikothedude** [comment]
> > I don't get it, why should they be better than engineering tools? When constructing isn't even science's job compared to engineering? Currently they(from what I've read) aren't really nerfed tools besides the jaws being unable to pry doors, they just have a different sprite, they're even unlocked in the same research node? Why should science get better tools than engineering for constructing things?
> 
> Main reason why they are faster is synth surgery. They are faster at surgery because they are... Made for more delicate job? Their construction speed is faster because that's code issue, that surgery steps have no code for list of tools and their workspeed and i don't really know how to code it🥲

theyre already faster because they have a 0.7 mod

**Comment by delingar** [comment]
> > > I don't get it, why should they be better than engineering tools? When constructing isn't even science's job compared to engineering? Currently they(from what I've read) aren't really nerfed tools besides the jaws being unable to pry doors, they just have a different sprite, they're even unlocked in the same research node? Why should science get better tools than engineering for constructing things?
> > 
> > 
> > Main reason why they are faster is synth surgery. They are faster at surgery because they are... Made for more delicate job? Their construction speed is faster because that's code issue, that surgery steps have no code for list of tools and their workspeed and i don't really know how to code it🥲
> 
> theyre already faster because they have a 0.7 mod

Engi tools have 0.7 too. But in case of synth-surgery they are still pretty slow

**Comment by Zergspower** [comment]
Not seeing why this should happen, these are already an upgrade to the **BASIC** tools which is science's baseline - dont use Engineering tools as your baseline. In no way should these ever out perform engineering tools which would be icly a far higher quality item

**Comment by GoldenAlpharex** [comment]
As others have already stated, this is basically just a powercreep on the science advanced tools. They were given those tools for convenience sake, they don't need to be just flat out better version of the engineering ones, when they're the ones that should be using those tools more often.

**Pull request closed without merging**
