### PR TITLE
VoidRaptor small fix - Deletes Space Bitrunner Den

### PR DESCRIPTION
**Pull request by Iajret**
## About The Pull Request
https://github.com/NovaSector/NovaSector/pull/670
https://github.com/NovaSector/NovaSector/runs/21389343509

image

## How This Contributes To The Nova Sector Roleplay Experience
Space bitrunners no more.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

### CODE REVIEW

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Map diff bot is not a valid proof of testing for mapping. Please compile and check the map in game.

**Comment by Iajret** [comment]
Sure thing.

**Comment by Iajret** [comment]
screenshot added.

**Comment by Zergspower** [comment]
yep i see that commit failed to push - lovely - yeah that shouldnt be there

**Review by Zergspower — APPROVED** [review]

**Comment by Zergspower** [comment]
rendered up fine on my end and looks good - should be good to go once Jolly can give it a look over

**Comment by Iajret** [comment]
> yep i see that commit failed to push - lovely - yeah that shouldnt be there

at least it gave me some laughs while i tried to fix merge conflicts with this map, lol.

**Review by Jolly-66 — APPROVED** [review]

**Pull request merged**
