### PR TITLE
[NONMODULAR] Nerfs the food tainting delay from 5 secs to 5 minutes

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title.

## How This Contributes To The Nova Sector Roleplay Experience

I seriously dont think a single person actually likes this mechanic. It serves absolutely no purpose other than to annoy, really, and its way too punishing with 5 SECONDS. ONLY 5 SECONDS. WHY? WHY FIVE SECONDS?? Thats barely enough time to even notice you dropped some food.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
it compiles
</details>

## Changelog

:cl:
balance: Food tainting delay has been nerfed from 5 secs to 5 minutes
/:cl:

### CODE REVIEW

**Comment by Ephemeralis** [comment]
Can't you just wash the food under a sink to remove the taint effect? 

I also kinda like the opportunity to get belligerent at people for throwing food at the floor as a cook/chef and that loses some gravitas when it's "just pick it up it hasn't been on the floor five minutes lol".

Totally get why you've made this change but I'm not sure it's as positive as it might seem in practice.

**Comment by SomeRandomOwl** [comment]
5 minutes is overkill, 39 seconds as said above is more reasonable, as well as yes, you can just clean food with a rag or sink and it's fine again

**Comment by Hemlock32** [comment]
It's the 5 second rule, not the 5 minute rule!

**Comment by nikothedude** [comment]
y'all are weird but sure i respect it

**Pull request closed without merging**
