### PR TITLE
Railgun PKAs can no longer be fired on-station

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
Prevents railgun PKAs from being fired on station by giving them the lavaland firing pin.

Additionally allows the restricted PKAs such as the grenade launcher and the railgun to be fired in Serenity's planet.

## How This Contributes To The Nova Sector Roleplay Experience
It's an infinite ammo hitscan gun that, unlike the others PKAs, is not balanced at all for space combat. It boasts a massive range with a high base damage of 100 (that splits into 60 for where ever it hits, which is as many as a mosin/sahkno) to people on space. I've been seeing a little trend of miners buying those and using it to 2 tap antags which is something that shouldn't be done for a gun designed for lavaland balance. The other PKAs are still something a bit broken but they usually have a counter to them while railgun just instantly nukes people from a screen away.

It being essentially a long range hitscan sniper rifle makes it way better than many alternatives, you don't even have to predict on where your target is moving towards unlike most of the guns such as hoshi or even battle rifles. Just click on them for the instant big damage provided that they're on space..

Monkestation, the downstream that originally made these PKAs also have them restricted due to it's power.

It can 2 people even in HoS modsuit or 3 for those in syndicate modsuits, which are designed to be really tough.

Some vids to represent my point better. I edited the screenshots out since they really don't show much.

https://github.com/user-attachments/assets/21c2a5a6-c688-4575-89e0-e71655efdf56

https://github.com/user-attachments/assets/f9ba1413-7fa7-4908-bef4-ef5399bdc875

As for the firing pin area addition, it allows miners to use the railguns and the grenade launcher in the planet in case they wish to mine in the planet while still being able to use special PKAs to snipe megadeers with.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
dreamseeker_C0vF56GGEr

</details>

## Changelog
:cl: Hardly
balance: Railgun PKAs can no longer be fired on station
code: Allows restricted PKAs to be fired in Serenity exterior
/:cl:

### CODE REVIEW

**Comment by OrbisAnima** [comment]
it works well in icebox, snowglobe and serenity?

**Comment by Hardly3D** [comment]
> it works well in icebox, snowglobe and serenity?

Should work okay on these areas
```
	var/list/wastes = list(
			/area/icemoon/surface/outdoors,
			/area/icemoon/underground/unexplored,
			/area/icemoon/underground/explored,
			/area/lavaland/surface/outdoors,
			/area/ocean/generated,
			/area/ruin,
```
Icebox and Snowglobe use ```/area/icemoon/underground/unexplored``` while Serenity uses ```/area/forestplanet/outdoors/unexplored```, the latter which is not in the list.
Good catch, I'll see about including Serenity's planet areas.

**Comment by OrbisAnima** [comment]
another question, why not fix it downstream?

**Comment by Hardly3D** [comment]
If you mean Monke, they already have it restricted since their initial PR
https://github.com/Gboster-0/Monkestation2.0/commit/234de98b08473e6ac92981cb83544574e9b7279d
I believe your port PR also mentioned giving it a pin but that might have been missed

**Comment by OrbisAnima** [comment]
Yeah, we originally tested it and since the railgun does 10 damage while inside the station it was deemed not a problem

**Comment by OrbisAnima** [comment]
To me it was weird that it needed the pin, the bombs, sure, they dont follow the pka code, but the pka already has a 90% damage reduction, in your test you had to break into space for it, and then you have things like a double barrel shotgun doing way more damage on point blank on the same conditions

**Comment by MajManatee** [comment]
This has no reason to be done to JUST one PKA. If you think one needs it, they all should have it.

**Comment by OrbisAnima** [comment]
I think the change to the firing pin for the bombs its okay, but for the railgun is innesesary, there are better weapons out there that dont have a 3 seconds cooldown and can mow down way more people (LMG being a big example)

What's the real use case of blocking it on the station? it already does 10 damage instead of 100 when you have pressure.

**Comment by Hardly3D** [comment]
I'd argue this is like comparing apples with oranges here, one's designed for on-station combat and crowd control while the other is meant to be used for lavaland combat. The gun cargo LMG costs around 2300 credits and is only accessible through a hacked supply console, as well as having little ammo and a lot of spread and recoil.

Railguns in the other hand can be easily mass obtained through bits of mining/boulder machine and are a lot accessible, less eyebrow raising and while it is for sure very weak on pressurized areas, it has been seeing a fair amount of use on space PvP by miners due to it's really long range and insane damage as well as being hitscan. Other PKAs like 3 cooldown PKAs can still be pretty strong for combat but that is a bit out of scope for this PR.

**Review by GoldenAlpharex — APPROVED** [review]
I'm good to give this a shot, I don't feel like much gets lost if you can't use a busted weapon like this outside of its intended area, that being lavaland/mining areas. Using it in space does indeed sound quite problematic for the amount of damage it does, its range and its unlimited ammunition. I don't see why people would want to use other things if they have access to one or two of these.

We'll test-merge it first, though, just to be sure.

**Review by FlufflesTheDog — APPROVED** [review]

**Pull request merged**
