### PR TITLE
Interdyne/DS2 Rising: Revengeance

### PR DESCRIPTION
**Pull request by sqnztb**
## About The Pull Request

Shuttledyne is back!

This is a resubmission of the pull that was opened at the end of October in the previous repo, but sadly never saw any playtime.  You can see the original history here - https://github.com/Skyrat-SS13/Skyrat-tg/pull/24645 - Dhu gave the greenlight to resubmit it here, so here we are.

The following is the original description and screenshots, but a lot of it is still relevant. **[EDIT]** The bits about the Icemoon Interdyne base aren't, as the base has been updated with #104 already, but the remaining 98% of the original PR is intact, with mostly behind the scenes path updates, some adjustments on the descriptions, and a few minor tweaks building off of Alos's Interdyne tweaks.

***
This PR completely overhauls the interdyne base and makes significant changes to DS-2 as well. I've posted a map of both stations below.

<details>

Interdyne:

DS-2:

</details>

I'm now going to briefly touch on the major changes and why I think they're good for the server.

1. The quantum pads to/from interdyne/ds-2 have been replaced with Interdyne's brand new very own cargo shuttle - which is capable of travelling to/from both DS-2 and the station. The ore silo and ORM boards have been removed from both bases and instead placed on the shuttle.

<details>

https://github.com/Skyrat-SS13/Skyrat-tg/assets/62350255/4e97a79f-ce16-4918-a76c-3e6263e9e850

</details>

2. DS-2's medical bay and mining equipment has been removed, along with their medical/mining spawners. This means DS-2 will have to rely on interdyne for materials and medical services. In place of where the medbay used to be is a much cooler robotics setup and an expanded engineering area.

4. Interdyne's entire base has been overhauled to be more medical-focused in an attempt to bring them more in-line thematically with their status as a pharmaceutics company. This means they no longer have an R&D setup. They have an autolathe, a medical techfab, and a colonial fabricator, but will have to rely on either DS-2 or the station for equipment from the circuit imprinter/protolathe. 

5. Interdyne is no longer a direct part of the syndicate by policy and these changes are meant to reflect that; so they've received new uniforms as well, courtesy of Zydras and Halcyon. Gone is the syndicate clothing they used to wear, and instead, new green/white medical-themed sprites are there in their place. They even get their own brand new InterDrobe clothing vendor. 

<details>

image

The neon green nitrile gloves ultimately didn't make it, but here are the new sprites.
image

</details>

6. Interdyne no longer has an infinite bluespace SMES, and instead will have to set up their own power every round, much like pretty much every other ghost role. This shouldn't be too hard, as the entire base can be powered with less than 60kw.

7. Icebox's version of interdyne is mostly untouched given DS-2 doesn't spawn on that map. I changed their spawn loadouts so that they spawn with the new clothing and replaced their SyndiDrobe with one of the new InterDrobe vendors; otherwise pretty much unchanged aside from removing some syndicate clothing that was laying around. I did add a syndidrobe resupply cannister and board so that while syndicate clothing isn't readily available on that map it's still accessible if they go out of their way to build a vendor.

8. Some extra relatively minor changes I should probably list for the sake of documenting them:
- I wanted to give the deck officer a special weapon fitting for their position, so I gave them a rapid-fire-syringe-gun kit in their locker; given interdyne is a pharmaceutics company this felt appropriate. 
- I made some tweaks to DS-2's armory. They have 3 shotguns and 3 sindano kits in there now, along with the kiboko, and brig officers spawn with wespes. This feels reasonable to me given every single person on Interdyne currently spawns with a sindano kit and some of them get makarovs on top of that. If some sort of conflict were to arise between the two factions I don't want Interdyne to just be able to steamroll DS-2.
- The deck officer and corporate liaison both have pets now, a chinchilla and a very sinister looking crab respectively.

## How This Contributes To The Skyrat Roleplay Experience

Interdyne received some pretty large policy changes a few months ago that changed their relationship with both the station and DS-2. Interdyne is no longer explicitly a part of the syndicate and is instead a neutral pharmaceutics company intended to be a kind of middleman/trader that deals between the syndicate and NT and operates in it's own self-interest, these changes should more accurately represent their status as a non-syndicate independent entity in-game.

As is, there's really not much incentive for Interdyne to interact with DS-2, and this has led to some amount of fighting between DS-2/Interdyne in-game. These changes should hopefully incentivize the two factions to actually trade with/rely on one another to some degree as this PR makes it mutually beneficial to do so and encourages healthier roleplay interactions.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

Posted some screenshots/videos above but here's a few more.

image

image

  
</details>

***

## Changelog
:cl:
add: Interdyne now has their own shuttle that can travel to/from DS-2 and the station.
add: Added new Interdyne clothing sprites to better represent their status as a neutral-aligned pharmaceutics company and to further differentiate them from the syndicate.
tweak: Completely overhauled the Interdyne lavaland base. They now have a new base more in line with their pharmaceutics theme.
tweak: DS-2 has had some pretty big renovations and will no longer be hiring doctors or miners; as they no longer have a medbay or any mining equipment.
/:cl:

### CODE REVIEW

**Comment by Zergspower** [comment]
i'll review the map part tomorrow

**Comment by Zergspower** [comment]
Some quick ones, i'll load it u p into the game to look closer tomorrow

<details>
<summary>Few minor tweaks first</summary>

Some disposal fixes

Atmos fixes
disconnected waste line
image

</details>

<details>
<Summary>DS2</summary>

Spare pipes
image

Disposals
image

**Comment by radarseas** [comment]
slightly unrelated but any chance of giving DS2 the internals boxes that Interdyne currently get? it feels like DS2 got left massively in the dust in terms of tacticool emergency breathing measures.. _they still get station-side internals boxes. instead of what actual syndicate field **agents** (contractors) spawn with, which is odd thematically._

the Interdyne drobe does have NIF installers right? _not I'm complaining, trade between the two is nice, its just urm, I feel people will **forget they exist otherwise**, they're rarely used even now._

I'm not sure if Syndrobes can be built or not. I know they can be refilled but I'm fairly certain you can't assemble them? unless that was fixed?

Its nice seeing Interdyne take a proper spin from TG's Interdyne to an actual faction of its own.

**Comment by OrionTheFox** [comment]
Just two icon placement things I noticed. _God I love that biosuit._

`modular_nova/modules/mapping/icons/obj/vending.dmi` - do we not have a master icon file for vending machines? It feels like it'd save you setting up overlays

`modular_nova/modules/mapping/icons/obj/headset.dmi` - This file is un-needed for a single state, if the mob sprite is in the master files' ears.dmi, the obj sprite should be too

Additionally, upstream made labcoats GAGS recently, the plain scientist labcoat should likely just use that system

**Comment by sqnztb** [comment]
> I do not think adding power to Interdyne is a good idea, either. As said in the previous go, it makes sense for survivalist roles, like Tarkon, but Dyne is chillvibes - and, more importantly, by it's aesthetic of a medical company will run chemistry and botany, which is by far the biggest power draw on the main station with a full supermatter to compensate.

Power still a topic of discussion that we're going to address.

> slightly unrelated but any chance of giving DS2 the internals boxes that Interdyne currently get? it feels like DS2 got left massively in the dust in terms of tacticool emergency breathing measures.. they still get station-side internals boxes. instead of what actual syndicate field agents (contractors) spawn with, which is odd thematically.

Should be doable.

> the Interdyne drobe does have NIF installers right? not I'm complaining, trade between the two is nice, its just urm, I feel people will forget they exist otherwise, they're rarely used even now.

They do! I actually brought this up in the initial release back on Skyrat.

image


> I'm not sure if Syndrobes can be built or not. I know they can be refilled but I'm fairly certain you can't assemble them? unless that was fixed?

This was also addressed when the update was originally submitted on Skyrat. The boards now exist and can they can be assembled if you can get your hands on one...

**Comment by Zergspower** [comment]
I only really have 1 request as everything else will get caught when the ghost PR comes in

A DS2 radio specific intercom for the prisoners, as we've had to rescue stranded ones many times in the past since DS2 had no idea there were any
image
maybe here

**Review by Zergspower — APPROVED** [review]
I dont think they need 2 different weapons on spawn, but the mapping part for the ruin is a pass

**Comment by sqnztb** [comment]
I hadn't previously touched the Icedyne, but Dhu reminded me about putting in an InterDrobe there. And the beds were swapped to doubles. For reasons.

**Comment by sqnztb** [comment]
Inducers back on DS-2. Removing an extra intercom. Interdyne gets parts and a bit more power at roundstart.

**Comment by radarseas** [comment]
some minor feedback for icebox Interdyne
capitalism
Icebox Interdyne vend has pricelock. _whoops!_ might want to set that to offstation = 1

whoops
DS2 bowmans on icebox in the spare equipment crate, minor thing though.

urm
DS2 telepad on iceboksss.

_For lavaland/general Interdyne_
Deck officer's bowman looks like deepspace one, minor inconsistancy though!

_no pictures for this one, sadly, but lavaland IP lacks spare agent IDs in case someone dusts, meaning they have to break into the corperate liason's office for more._

Deck officer lacks spare parts of their uniform and still has the old pre-nova ones.

**Comment by sqnztb** [comment]
Vendor ✅
Icebox headsets. Good catch, forgot about those. ✅ 
Telepad. Pretty sure this was a merge conflict oopsie. ✅ 
DO Bowman, very good catch on this one, too. ✅

**Comment by SovietSpaghetti** [comment]
Removing the teleporter in favor of a shuttle that can only be moved from 1 of its 3 destinations seems really tedious. Less than half an hour in and I've already had an issue of someone being at the station and I can't move it to get to DS2 because it'll strand them. Same with the silo and ORM being there. If only interdyne gets mining equipment (which they can't print any upgrades of wihout help/ if no one on DS2 is awake because they only get a medical fab), why can't the silo and ORM just be there instead?

**Comment by sqnztb** [comment]
>  Less than half an hour in and I've already had an issue of someone being at the station and I can't move it to get to DS2 because it'll strand them.
You know y'all have radios. They won't be entirely stranded. They can either radio for it to be moved back to Interdyne or go via public mining. You know. The way you'd get to the station to do business right now. The reason the silo's on the ship is because moving the silo from z-level to z-level allows both Interdyne and DS-2 to link their machines to the same silo. You can't link to a silo that's off the z, but once the link is made, the silo can be moved and the link remains.

Ingredients are right here:
image

**Comment by AsterTX** [comment]
Honestly I think it's genuinely a good idea but the way it's gone about seems poor. It actively makes mining harder on the few miners that exist only giving them basic cutters to god forbid satchels from the colony fabricator... Removing the once independent nature that almost every dyner loved to being forced to cooperate with the terrorists that they wanted to fully separate themselves from. It removed alot of actual research most could do and now it has to intertwine with base-building and research begging... It doesn't feel like the "Top-Tech Pharmacy Company" and instead it feels like a NT knock-off trying to make pick ourselves up from the ditch that we over drank in. Again it's an interesting step forward but one that seems to defeat alot of the personal goals that most active Interdyne players had wished for.

**Comment by sqnztb** [comment]
Just to address a couple of small pieces:

 Removing the once independent nature that almost every dyner loved to being forced to cooperate with the terrorists that they wanted to fully separate themselves from. It removed alot of actual research most could do and now it has to intertwine with base-building and research begging... It doesn't feel like the "Top-Tech Pharmacy Company" and instead it feels like a NT knock-off trying to make pick ourselves up from the ditch that we over drank in. Again it's an interesting step forward but one that seems to defeat alot of the personal goals that most active Interdyne players had wished for. For a long time we've been wanting to push ourselves away from the DS-2 entirely, waiting for their bluespace miner appear so we can trade weapons and strange gadgets.... But now it seems like you've slipped out every expectation and forced us back into begging or working for the DS-2 once more, I find it shameful now that we're going to have to rely on new power play for the syndicate as we were SO CLOSE to removing.

> It actively makes mining harder on the few miners that exist only giving them basic cutters to god forbid satchels from the colony fabricator...

I'm genuinely curious about how much *harder* it makes mining. Advanced cutters have a faster fire rate (around 50%) and more ammo (40 vs 100 shots per full charge), but other than that they are completely equal. And the satchels from the colony fab? Uh...

image

Yeah god forbid you have satchels of holding 10 seconds into a round (because gold and uranium are both available in virology)

Regarding the whole lore split between Interdyne and the rest of the Syndicate: As it stands now they're separate but still supply the medical, because it's still profitable. It is still mutual cooperation as of right now. I understand that you (and others) are upset over the fact that we lost the ancient protolathe and circuit imprinters, but using the radio to ask for DS-2 to print a handful of T4 parts or a MODsuit module won't kill you. Interdyne isn't a slave to DS-2 any more in the current interation than DS-2 is slave to Interdyne being *completely reliant* on them for materials now.

**Comment by AsterTX** [comment]
369f41155056c6a2b04356d29f498267 (1)
ac3e546aeb0779a8d9e12551fbe6db25 (1)
ed7c4fc557d98d0f8e22f3ef4046496b (1)
eda0ca71f23b26666e30834996ca83a1 (1)


Again I don't want to be an asshole about it, but this is what I knew what was going to happen.

**Comment by AsterTX** [comment]
eda0ca71f23b26666e30834996ca83a1 (1)
369f41155056c6a2b04356d29f498267 (1)
ac3e546aeb0779a8d9e12551fbe6db25 (1)
ed7c4fc557d98d0f8e22f3ef4046496b (1)



(Edited names out) Again I don't want to be an asshole. But this is what I feared from the word go, is the dyne being denied any basic help from their supposed partners. I feel as if they should be more.... Open to getting parts for themself, it can be worked around with xenoarch, making dyners adapt and work with what they got.... But it shouldn't having to deal with bad faith like this example.

**Comment by SovietSpaghetti** [comment]
In the years I've been playing Interdyne and DS-2, the squabbling only really got bad when they tried to make the two more separate. Before that they would actively share ore silos, equipment, take each other to each other's medbays etc., up until the point where Interdyne was made a neutral faction and you weren't allowed to move between DS-2 and Interdyne. Then they would grab DS-2 by the proverbial balls and demand things in exchange, or just disconnect the teleporter entirely at the slightest offense under the guise of 'well we aren't part of you anymore, so we don't have to put up with you, and are entirely self-sufficient on our own'. And even now, with them designed to be as codependent as possible, it's back. Even if you just go the station when DS-2 is being stingy, it's still a lot less convenient, and you'd likely have to go to several departments to beg for the stuff you want that you could normally all get from 1 lathe. Get bartering material (and EVA equipment if it's blueshift). Take shuttle ride. Go to robotics to ask for MOD equipment or mech parts. Go to the science desk and ask them to print stock parts. Walk to engineering to get upgraded tools. Go to cargo for upgraded mining equipment. Finally head back to the shuttle, realize someone on Interdyne recalled it and it has to be sent back. Wait for a response. Give up and trudge back through lavaland with your gear to the base. Realize you forgot something.

Even with the reasoning of them being 2 separate entities, it's just not as fun or convenient to have to go beg someone for something every time it's not in your explicit and thin lane. The convenience of being able to 'just do whatever' on your own was a big draw of Interdyne/DS2 for me, and this feels like it does away with that in favor of more Eris-style 'departmental' squabbles in order to get anything done.

**Comment by nikothedude** [comment]
please add separating windoors to interdyne's botany

**Comment by radarseas** [comment]
Thing A

Thing B
minor thing but digi sprites with the biosuit are a _bit borked_.

**Review by Zergspower — APPROVED** [review]

**Pull request merged**
