### PR TITLE
Changes mold mobs into slime mobs

### PR DESCRIPTION
**Pull request by honkpocket**
## About The Pull Request

This is the first half of a project I'm interested in developing, which is revamping/beautifying the moldies event.
The concept is that instead of a nondescript mold infection the mid-round antagonist is a slime invasion instead.

I'm really curious to see this PR tested out, and if its successful a follow-up artsy PR can be made.

## How This Contributes To The Nova Sector Roleplay Experience

Combat with slimes has a lower entry point, meaning fire extinguisher off the wall. But it also allows for various different methods of attack. Various jobs can do their work to prepare against a slime army, like the chemist getting to prepare special chemicals that have damaging effects, or atmosians that can tamper with the temperature or release gasses.

Besides combat variety, I've also greatly expanded the list of possible mold spawn locations, and nerfed how big it is on initial spawn. This way it can be handled quicker, like the space vines event - but not as effortlessly.

The slime mobs are snowflaked to be deleted on death, and they got to keep the special on-hit effects the old mobs had. Which means they still inject teslium, light you on fire, make you sick, and et cetera.

## Proof of Testing

<details>

<summary>Screenshots/Videos</summary>

 dreamseeker_g4Iy0Sz7Xa

</details>

## Changelog

:cl:
add: The mold core now spawns slime mobs to defend itself, instead of the old mobs.
del: Removed the old mold mobs: oil shamblers, mosquitos, centaurs.
/:cl:

### CODE REVIEW

**Comment by HoodMilk** [comment]
To be honest it spawning slimes makes a lot more sense for a mold than randomly spitting out spiders or mosquitos

**Review by SomeRandomOwl — COMMENTED** [review]
I dont think this is the way we should go with molds, we should balance the existing mobs rather than removing. I will always be against things that actively removes things for no real good reason without trying to balance them first. Mold is in an alright spot but probably just needs some numbers tweaked. 

I am going to talk to a few other maints but chances are I'm going to move to close this in favor of wanting to rebalance rather than remove.

**Comment by honkpocket** [comment]
> we should balance the existing mobs rather than removing

but they're ugly and boring :/

**Comment by GoldenAlpharex** [comment]
I think a good way to go about it would be to try and see if we couldn't come up with new designs for the existing mobs, to mold-ify them more instead, so that it's not just slimes you have to fight.

**Comment by GoldenAlpharex** [comment]
> I think a good way to go about it would be to try and see if we couldn't come up with new designs for the existing mobs, to mold-ify them more instead, so that it's not just slimes you have to fight.

By new designs, I'm thinking mostly sprites, first, and then we can see about modifying their mechanics as well.

**Comment by honkpocket** [comment]
> adult slimes take like 4 extingusher sprays to kill from adult and the split

Would love to see a clip of you testing the PR. Go ahead and show me how easy it is.

**Comment by honkpocket** [comment]
> I think a good way to go about it would be to try and see if we couldn't come up with new designs for the existing mobs, to mold-ify them more instead, so that it's not just slimes you have to fight.

I want to add some filler mobs that can soak up bullets pretty well, unlike slimes. But I prefer to keep the slimes the star of the show.

**Comment by Hemlock32** [comment]
I can definitely agree that slimes are at least more thematic than the existing mobs both visually and through their method of attack
Can't really say they'll be any easier than the existing mobs, just, different. A lot of weapons will become inefficient alongside the new options, so, it balances out to just being, different, rather than easier.

**Comment by GoldenGardens** [comment]
This honestly seems like a fat nerf, rather then a rework

**Comment by honkpocket** [comment]
I'm rapidly losing my will to continue this project because of the amount of boo'ing comments I'm getting on a PR that clearly states its goal is to test balance against high player counts, something I can't test on my own, and not something I want merged in this exact state.

**Comment by chemistrymain3** [comment]
> I dont think this is the way we should go with molds, we should balance the existing mobs rather than removing. I will always be against things that actively removes things for no real good reason without trying to balance them first. Mold is in an alright spot but probably just needs some numbers tweaked.
> 
> I am going to talk to a few other maints but chances are I'm going to move to close this in favor of wanting to rebalance rather than remove.

endlessly tweaking numbers on boring walk forward and hit you mobs that do nothing other than walk forward and hit you is not the way to go

mold needs a redesign and this is the beginnings of an approach-variety in its spawn locations, and what it's capable of, is a good place to start

'without trying to balance them first' is effectively irrelevant- the mobs suck ass as they are currently, and it's not because of the numbers or doing too high/too little damage, it's that they're boring, uninteresting, and have bad sprites

**Comment by honkpocket** [comment]
Needs more work and I can take my time as I atomized useful parts of this PR already.

**Pull request closed without merging**
