### PR TITLE
Revert new smartfridge UI (#3916)

### PR DESCRIPTION
**Pull request by FlufflesTheDog**
This reverts commit 2a78722ac60481c36a000db6b3dabc9c75075a1d.
## About The Pull Request
Reverts #3916
Unbearably loud stacking sfx when vending multiple items, lack of names for visually-nondistinct contents, and stacking based on type rather than name all makes this much more of a downgrade than this is worth

### CODE REVIEW

**Comment by FlufflesTheDog** [comment]
It isn't done in a modular way, and is meant to be a stop-gap until it gets improved upstream.

**Comment by Sadboysuss** [comment]
that's so scuffed

> Unbearably loud stacking sfx when vending multiple items
maybe make an issue report on this upstream?

**Comment by FlufflesTheDog** [comment]
It is a [known issue](https://github.com/tgstation/tgstation/pull/85063#issuecomment-2252998628), but might help get it fixed if there's an actual report, true

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/85366

**Comment by Lutowski** [comment]
UI was changed & merged on TG after feedback, consider looking at it again.

**Pull request closed without merging**
