### PR TITLE
Free Bug DLC: New Antennas & Snouts & Body Marking

### PR DESCRIPTION
**Pull request by avimour**
## About The Pull Request

More bug antennas, a new snout, remixed snout. and a body marking!  

## How This Contributes To The Nova Sector Roleplay Experience

More customization for bug players! Some of these can also be used for non bugs, such as chitin markings being good for ball-jointed markings.

## Proof of Testing
Setaceous Antenna

bug dlc 2

Medium Setaceous Antenna

bug dlc 3

Geniculate Antenna

bug dlc 6

Eye Antenna (If anyone knows how to put ears on top of eyes please let me know. Otherwise these still look cool without the overlap)

bug dlc 1

Dragonfly Snout

bug dlc 4

Bug (No Antennae)

bug dlc 5

Chitin

bug dlc 7

## Changelog
:cl:
image: New Ears: Setaceous, Medium Setaceous, Geniculate , and Eye
image: New Snouts: Dragonfly, Bug (No Antennae) 
image: New Body Marking: Chitin
/:cl:

### CODE REVIEW

**Comment by ApplePlastic** [comment]
It's.. fucking.. peak..

**Comment by Valerioninithis** [comment]
thank you! bug choices were so limited, it's great to have more

**Comment by nikothedude** [comment]
thats a great way of showing dirs

**Comment by avimour** [comment]
> thats a great way of showing dirs

it also lets me show various colors in one instance instead of making a ton of gifs of people turning around!!

**Review by GoldenAlpharex — APPROVED** [review]
Yeah, this looks fine to me!

**Pull request merged**
