### PR TITLE
Fix Syndicate Spacesuit Names

### PR DESCRIPTION
**Pull request by LordHookie**
## About The Pull Request

Fixes the names of the engineering and medical syndicate space helmets referring to them as a generic _'black space helmet'_, despite being separate items, and fixes the medical syndicate space suit inexplicably being called a _'green space suit'_ despite objectively not being green.

Naming schemes follow the only-correctly-named Black Engineering Space Suit's naming pattern.
Why in the name of god are there so many syndicate space suit variants? They're hardly used for anything!

## How This Contributes To The Nova Sector Roleplay Experience

Accurate labels and consistent naming schemes are good and prevent confusion among players. Also, I'm working on a PR that involves these, and their names being incorrect is going to drive me **fucking insane.**

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

image

image

</details>

## Changelog

:cl:
fix: The Syndicate Medical Space Suit is no longer labelled a 'green space suit' despite being a noticeably non-green color.
fix: Syndicate Medical and Engineering space helmets now display themselves as such.
/:cl:

### CODE REVIEW

**Comment by LordHookie** [comment]
> You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

That's what I'm trying to do, github-actions..

**Comment by GreytideSkye** [comment]
for reference, the suits being modularized over are at [NovaSector/code/modules/clothing/spacesuits
/syndi.dm](https://github.com/NovaSector/NovaSector/blob/4de5ac639218263150199c5678ceefaa078a80d3/code/modules/clothing/spacesuits/syndi.dm#L144 )

**Comment by LordHookie** [comment]
> for reference, the suits being modularized over are at [NovaSector/code/modules/clothing/spacesuits /syndi.dm](https://github.com/NovaSector/NovaSector/blob/4de5ac639218263150199c5678ceefaa078a80d3/code/modules/clothing/spacesuits/syndi.dm#L144)

this reminds me i don't need to have their icon sprites. gonna fix that now since i'm pretty sure everyone's asleep
so used to copying the entire thing at once, not so used to this kind of highly modular code.

also check out this gem
image

**Comment by LordHookie** [comment]
... " Error: The operation was canceled."
Whar.

**Comment by LordHookie** [comment]
Aaannnd it fixed itself. OK.

**Comment by LordHookie** [comment]
> Good fix, and done properly, however this is an upstream bug isn't it?
> 
> It looks like TG changed the icons 11 months ago and didn't update the names. You'd be better off making a PR on https://github.com/tgstation/tgstation so we do not have to add this to our overrides, instead opting to directly modify the TG code.
> 
> edit: wow that said 11 years not months. Has this really been around that long?

True. Sorry, my brain shut off at the implication I would have to interact with TG.

Nah, really, thanks, though, I just didn't even think of that. I'll open it there.

**Pull request closed without merging**
