### PR TITLE
Fixes a few missing items on icebox's interdyne base

### PR DESCRIPTION
**Pull request by YehnBeep**
## About The Pull Request

Fixes missing GPS units (can't be printed by the ancient protolathe) and oxygen/nitrogen canisters on the icebox interdyne base.

GPS units are higher compared to the lavaland base as there are more spawners on icebox. Canisters are at exact parity.

## How This Contributes To The Nova Sector Roleplay Experience

~~GPS units cannot be constructed with the equipment present but are pretty important.~~ Ok there is a way, but, still, nice to have a few. Canisters can be worked around but it's just nice to have.

## Proof of Testing

<details>

image

image

image

</details>

No code changes.

## Changelog

:cl:
fix: Fixed icebox interdyne outpost missing GPSs and canisters.
/:cl:

### CODE REVIEW

**Review by SomeRandomOwl — CHANGES_REQUESTED** [review]
Still needs screenshots of the code running properly and the map compiling, the changes need to be visible

**Comment by YehnBeep** [comment]
Screenshots of it running added

**Comment by YehnBeep** [comment]
...Though I realized I forgot to push. But the screenshots are up to date.

**Review by sqnztb — COMMENTED** [review]
GPS units can be printed via an exosuit fabricator (which you can print the board for that from the ancient circuit imprinter.) Interdyne gets to use the MODsuit GPS units. These are normal size (instead of small) but they work when placed inside of your bag. 

I think seven GPS units is a bit much. I'd axe the single ones on the left rack and the one in the science wing and I think we'd be good to go.

**Comment by YehnBeep** [comment]
Done

**Review by sqnztb — APPROVED** [review]

**Review by Zergspower — APPROVED** [review]

**Pull request merged**
