### PR TITLE
[MIRROR] Bow Update: Fletching instruction manual, bows using projectile damage multipliers, unhardcoded bow sprites, hot pink death [MDB IGNORE]

### PR DESCRIPTION
**Pull request by NovaBot13**
Original PR: https://github.com/tgstation/tgstation/pull/84435
-----
## About The Pull Request

Adds a new crate to the Service section of cargo. The Fletching and Bow-Making Starter Kit. Comes with some materials and a fletching instruction manual.

The manual teaches you how to make shortbows (18 force from normal arrows utilizing projectile multipliers), arrows, holy arrows (but you need a divine bow to make them), quivers (but they only hold 10 arrows), plastic arrows and violins. For reasons.

image

### Fixes

Bows now no longer utilize hardcoded sprites for their loaded sprite. Now they use overlays. 

Bows properly become undrawn once fired. No longer can your bow magically launch arrows by sheer force of will.

## Why It's Good For The Game

Initially I just wanted to provide a way for bow wielding chaplains to produce additional arrows for their bow. Running out of those always felt pretty lame. But then I got to thinking; actually, I kind of want to LARP sometimes as an archer. I think that'd be kind of goofy and fun. So I bundled that together into a solution for both.

The shortbow is really, really not meant to be a meaningful weapon. It's just kind of silly, and meant to let people pretend to be Robin Hood and occasionally hurt someone in a workplace accident. I'm particularly thinking of clowns being the perfect users for this with their clumsy trait. I will make this weaker if I have too.

(I am not, at this moment, redoing flaming arrows okay? I saw the code comment. I know. Not right now. tralezab, if you have any flaming arrow sprites lying around, please let me know.)

## Changelog
:cl:
add: Fletching starter kit! Make your own bow, shoot your friends in an unfortunate workplace accident. Replace all those holy arrows you lost.
fix: Bows now properly undraw once they have fired an arrow.
code: Bows now utilize overlays in order to display loaded arrows. Unique overlays per arrow.
/:cl:

### CODE REVIEW

**Comment by Ephemeralis** [comment]
Awful changes all round. Not worth merging given our custom content, can probably avoid.

**Comment by CliffracerX** [comment]
This seems quaint, and the code improvements at least are worth salvaging, even if we modularize out the archery toolkit itself.

**Comment by Nerev4r** [comment]
our bows are in a pretty great spot rn ngl

**Comment by TetrakoHateThis** [comment]
While this is kinda iffy with the ability to craft bows and arrows here belonging to reagent forging, it does also give crafting recipes for a new non-lethal ammo type, as well as finally allowing a means to craft holy arrows.

**Comment by FlufflesTheDog** [comment]
Well we gotta do something with this, so something has been done. Open to feedback but just not merging it is sorta out of the question.

- Code improvements implemented, our bows use the nifty dynamic overlays (we currently lack sprites for drawn bone/ash/bronze arrows, falls back to normal arrows)
- The cargo fletching kit is still around, but it's been made significantly cheaper since bows are normally available pretty easily already, and the stuff it offers is much weaker in comparison. 
- Cleaned up some duplicate or misleading recipes- you cannot craft a longbow by hand, that (and easier access to arrows) are gotten through forging as it is currently

Also, our custom bows (namely the ashwalker bow) have nicer hitboxes so you don't have to pixel hunt for the frame of the bow to load an arrow, and the ammo hud updates more consistently for bows (honestly why is it even there, you can just look at the bow)

**Comment by TetrakoHateThis** [comment]
> Also, our custom bows (namely the ashwalker bow) have nicer hitboxes so you don't have to pixel hunt for the frame of the bow to load an arrow, and the ammo hud updates more consistently for bows (honestly why is it even there, you can just look at the bow)

Would this mean the normal longbows from forging/renaissance crate would also get the better hitbox too?

**Comment by FlufflesTheDog** [comment]
> Would this mean the normal longbows from forging/renaissance crate would also get the better hitbox too?

Normal bows (longbows, "bows", and the new shortbows, all use the same sprite) already had an extended hitbox. The only thing missing it now afaik is upstream's new divine bow

**Comment by TetrakoHateThis** [comment]
As long as there's parity with bow hitboxes, then I think it's more or less good. The book can serve as access to additional arrow crafting given there's #3991 coming with more new arrows requiring the book. The new plastic arrows having 50 stamina damage is good as a more non-lethal oriented option for bows, and we have better means of getting the bows/quivers anyway. t. Someone who often uses bows in game.

**Review by FlufflesTheDog — APPROVED** [review]

**Pull request merged**
