### PR TITLE
Ouroboros rejigging

### PR DESCRIPTION
**Pull request by Ketrai**
## About The Pull Request

General map update for Ouroboros. This PR aims to improve quality of life on Ouroborus by making it a little more spacious. Rejigging some of the departments to be easier to traverse and work in, without affecting the map theme too much. Some notable changes that are aimed to be included.

**NOTE - The floor decals being rainbow colored is because of some kind of /TG/ event I'm not sure how to turn off!**
**NOTE 2 - There may still be disposal pipe, lights, cameras and walls being weird someplaces. I got rid of any breaches and fixed a lot across like 10+ debug testing rounds and map passes, including stuff that was broken that wasn't caused by my changes. Imagine I increased the station a tile in every direction symmetrically, so bear with me as I pieced everything together again!**

- Generally increase the size of some department hallways and high traffic areas, like getting rid of single doors where double doors make sense.
- Expand the amount of space chemistry has available to them, being a space intensive department.
- Rework the kitchen to be more spacious and on the same floor as the main kitchen counter.
- Add more space to the bar, mainly allowing the bartender to enter the counter without having to step on the chef's toes.
- Fix xenobiology starting breached.
- Improve the size of the security meeting room to let sec officers fit in a bounty pad, and so you can have 8 sec members + captain + NT rep comfortably attend a meeting together.
- Similar increase the size of the meeting room to allow 6 heads of staff, captain, nt rep, blueshield to comfortably attend the meeting, with more space to move around without kissing captain shoes (as per the cap's regret). Ditto for the break room.
- Add the missing 6th security officer locker.
- Remove and addition of missing/misplaced shutters. Other general fixes like lights, walls etc.
- Gives the poor NT rep an actual room rather than forcing them to sleep in the equivalent of a broom closet.
- Extra light switches, notably the ones added in #2191 as well

## How This Contributes To The Nova Sector Roleplay Experience

Makes the map more enjoyable to play by addressing some general issues brought up by the community and certain things I noticed to be missing. Especially given that when this map comes up, it often times tends to be at 80-90 pop, only for the round to gain players, resulting in 120+ people playing on this map, it's nice if there's a little more space to accommodate that kind of player count.

## Proof of Testing

<details>
<summary>

bar

- Gives bartender more space. Moves kitchen from upper to lower, changing the layout to be more friendly to modification, and provide space for up to three people. (2 chefs + a borg) Also adds a service area for cargo to deliver to the kitchen, as well as offering more maint entrances and making other maint entrances more accesible for people besides the chef. Whilst the kitchen previously was nice looking, it sadly eliminated interaction between the chef, botany, and the clients at the counter by being relatively isolated on the upper level.

kitchen-upper

- Freezer is now upper. More standardized rectangular size with a maint exit for sneaky chefs. Provides a grub-dash counter for quick snacks, custom orders, to watch the chef grill and chat, as well as a private dining space that can be locked off with shutters.

Botany

- An extra row of space so botany can properly set up auto pipes if they want. Less bottlenecking when dragging stuff like crates or tanks.

library

- More space to play games together, and a few extra painting slots.

Interlink Test

- Just to show I tested if the shuttle was still aligned.

Robotics

- Given robotics might have mechs, borgs, roboticists walk around at the same time, this adds a little extra space for them to move in.

barber

- Barber can now attend to clients from behind without standing in the door frame, allows for better roleplay.

bridgeandntrep

- More space in the bridge so things aren't overlapped on top of the NT logo, and it may be less crowded with 6 heads of staff, some seccies, nt rep and blueshield gathering. In the corner you can see the NT rep went from a 1 tile bedroom, to a 6 tile bedroom.

secmeeting

- Space for 6 heads of staff, cap, nt rep, blueshield, and plenty of space to move around. Break room a bit more spacious, it's the bridge after all.

Triage

- More space to move around in the medbay triage hall given people will be dragging around rollers etc, or having to work in close proximity on patients. It also just makes sense if you're trying to avoid infections!

chem

More space in lower chemistry. Note, in total this adds chemistry's blueprint to the largest of all stations. But I'm assuming people won't be able to use the weird upper level properly due to its shape, and that chemists are generally not going to get rid of the viewing hole into the lower deck. The lower deck was rather tight space wise (it's 115 tiles in total just for lower, 186 tiles if you count upper and open spaces!).

departures

- A little extra cafe and a new table to put stuff onto whilst waiting for the shuttle. There's already a cafe on the map, but I just like having one in an area where it might see natural use.

brig entrance

- 2 wide entrance to make entering and leaving easier given the gate doesn't let everyone through.

security

- Meeting hall supporting 10 people in total. It won't be enough if cap, rep, and blueshield decide to attend a full meeting, but it's sufficient for 5 officers, warden, hos, two dets when it previously wasn't. There's more wiggle room so you don't have to floor yourself to move past people on chairs. Includes one extra tile next to the machine frame so seccies can make a bounty receptacle next to the console. North you can also see that the sec storage has a 6th locker now. There's only 5 seccies currently, but maps seem to follow having 6 lockers more often.

xenobio

- Just to show xenobio does now indeed, not start breached on roundstart.

</summary>
  
</details>

## Changelog

:cl:
qol: Makes Ouroboros quite a bit more spacious with area overhauls! (Ouroborous changelog start)
qol: Size increases to botany, robotics, chem, security meeting room, security hall, bridge, bridge meeting room.
qol: Increases the kitchen size, moving the kitchen to the same level as the main counter. Also increases bar size.
qol: Gave the bar their own side entrance. NT rep should now have an actual bedroom.
qol: Adds a bunch of extra light switches as well. (Ouroborous changelog end)
/:cl:

### CODE REVIEW

**Comment by Ketrai** [comment]
> Do provide screenshots of each affected area when best possible, Make sure its in game screenshots and not editor screenshots.

I will once I get done with it, given things change frequently still!

**Comment by sqnztb** [comment]
Changelog needs to be descriptive.

Also:
> [...] and that chemists are generally not going to get rid of the viewing hole into the lower deck. [...]

... Yeah we are? Like. We get rods and floor tiles already pre-mapped in. There's no reason why we wouldn't. Takes ten seconds.
image

**Review by sqnztb — COMMENTED** [review]
image
Floating sinks in the barbershop.

image

Multiple disposal issues. Missing pipes. Y-junctions used in place of regular segments.

image

Light and a fire alarm on the door. Camera on the backdoor. Also the cabinet is in front of the door as well? Move it up one tile.

image
Areas.

image

Library lounge area is extended into maints. Same with the private study.

image

More area issues.

image

Another area gripe. This block that the intercom is on should be the fore hall. it's completely inaccessible from being inside the library.

image

More broken disposals.

**Comment by Ketrai** [comment]
@sqnztb The sinks were like that, with a little imagination they can be seen as washing basins, so I kept them that way.

Thanks for pointing out more disposals issues. Can be pretty hard to see under all the pipes. I doubt it's the last of them, but hopefully smushed at least 95% of the broken pipes. I don't know what the difference is between Y junctions and regular ones. I've replaced them, they were just what was being used around the bar before I started tweaking it.

**Comment by OrbisAnima** [comment]
oh, another issue I found is that the map had a lot of air canisters, but nearly no scrubbers at hand!

**Comment by Ketrai** [comment]
> oh, another issue I found is that the map had a lot of air canisters, but nearly no scrubbers at hand!

Including with the ones that can be found in the main hallway?

**Comment by Ketrai** [comment]
> heads up, I recently did a upgrade run on ouroboros and the cameras were fucked enough to have to walk. The biggest issue with them was the bitrunner one. Wouldn't be a bad idea to do a mock upgrade run with cameras to check they are in order, besides an ai run

I checked the bitrunner den, there's a camera present there so I'm not sure what the issue you mean is here?

**Comment by Ketrai** [comment]
Added some light switches where it makes sense, most notably the ones as mentioned in #2191

**Comment by Ketrai** [comment]
image
*pain.

If I may, suggest #2191 gets reverted and this can please get tested on the live server? I've added the exact same light switches as that PR and more.

**Comment by SomeRandomOwl** [comment]
> image *pain.
> 
> If I may, suggest #2191 gets reverted and this can please get tested on the live server? I've added the exact same light switches as that PR and more.

that wont remove the merge conflict markers on the map iirc

**Comment by Ketrai** [comment]
**Notice!**

Screenshot updated for sec meeting area. I made it a LOT bigger given that it's the most common security complaint currently!

**Comment by sqnztb** [comment]
@Ketrai How close to being 'done' are we on this? Is it in a spot to where we can pause any further updates so I can give another review for merging?

**Comment by Ketrai** [comment]
> @Ketrai How close to being 'done' are we on this? Is it in a spot to where we can pause any further updates so I can give another review for merging?

Feel free to re-review. Most of the updates barring sec have been either adding missing items or fixing disposal pipes/apcs. I've observed like 5 rounds since, so I'm pretty confident all the pipes are working now.

**Comment by sqnztb** [comment]
No more commits past this point, please. Going to do a thorough testing of it locally tonight.

**Comment by sqnztb** [comment]
Okay so this is a non-exhaustive list of everything that I've found, I'm just too tired of looking at it at this point.

<details>
<summary>atmos piping issues</summary>
morgue

image

pharmacy

image

air tank behind the chapel not connected

image

viro air supply not connected also this is hideous but whatever

image

this is right next to botany... this is also a wiring/cabling issue. 

image


</details>

<details>
<summary>cameras/intercoms</summary>

not 100% if this is an issue or wonkiness with the camera view overlay, but there's this vertical row at arrivals that doesn't show camera coverage.

image


intercom gaps, ideally every main hallway has intercom range - 

image

image

image

image

image

</details>

<details>
<summary>apc/air alarms</summary>

just per the debug readout. not EVERYWHERE needs an apc/air alarm, but a couple of notables: morgue, bridge hall (`/area/station/hallway/secondary/command`)
```
AREAS WITHOUT AN APC:
/area/station/asteroid
/area/station/science/ordnance/freezerchamber
/area/station/science/ordnance/burnchamber
/area/station/cargo/miningdock
/area/station/hallway/primary/central/fore
/area/station/maintenance/central
/area/station/security/brig/upper
/area/station/maintenance/aft/upper
/area/station/security/processing
/area/station/security/prison/upper

AREAS WITHOUT AN AIR ALARM:
/area/station/asteroid
/area/station/maintenance/department/science/xenobiology
/area/station/cargo/miningdock
/area/station/science/ordnance/testlab
/area/station/maintenance/port/lesser
/area/station/hallway/primary/port
/area/station/maintenance/department/cargo
/area/station/maintenance/port/fore
/area/station/maintenance/port/greater
/area/station/maintenance/port/aft
/area/station/maintenance/port/central
/area/station/maintenance/fore/lesser
/area/station/hallway/primary/central
/area/station/maintenance/department/bridge
/area/station/maintenance/department/eva
/area/station/hallway/primary/starboard
/area/station/medical/morgue
/area/station/security/brig
/area/station/maintenance/department/security/lower
/area/station/medical/chemistry
/area/station/maintenance/starboard/greater
/area/station/maintenance/starboard/lesser
/area/station/science/research/abandoned
/area/station/hallway/secondary/command
/area/station/maintenance/department/electrical
/area/station/maintenance/central
/area/station/security/brig/upper
/area/station/maintenance/aft/upper
/area/station/maintenance/department/security/upper
/area/station/security/prison/upper
```
</details>

<details>
<summary>area issues</summary>

image

</details>

<details>
<summary>disposals</summary>

behind the kitchen/cargo

image

central hall

image

medbay, upper pharmacy

image

garden

image

toilets. this is also a wiring issue, there's no cable connection here. (not shown in this snip)

image

hfr/security iirc

image

medbay, lower pharmacy

image

medbay break room

image

</details>

**Comment by Jinshee** [comment]
could some additional jiggling be spared for adding a water source to the science/xenobio department? they dont actually have one mapped in, funny enough

**Comment by ALambrechtsStudent** [comment]
@sqnztb Odd there were no errors thrown for those scrubbers. Also, how did you get a view with just the pipes? I couldn't see that option anywhere in strongdmm or with mapping debug verbs, it would've been super useful. I'm amazed there were still that many disposal issues ;-;

**Comment by Ketrai** [comment]
> could some additional jigging be spared for adding a water source to the science/xenobio department? they dont actually have one mapped in, funny enough

Done.
Fixed all the other issues in the post from @sqnztb as well. Including a few other disposals I noticed.

**Comment by sqnztb** [comment]
props to @FlufflesTheDog for helping test and debug disposals.

<details>
<summary>disposal issues - </summary>

medical break room still a problem. there's no trunk under the bin.
image

these junctions in the bar I believe needs to be flipped to route south since it's spitting stuff out in the bar.
image

similarly, these junctions need to flow west, I think. bar/janitor's closet
image

junctions again, kitchen.
image

and then the hop office.  should have a mailsorter that sorts to the hop office and passes everything else through. 
image

nt rep's office. isn't breaking anything but it shouldn't be a junction, swap to a normal pipe.
image

</details>

**Comment by FlufflesTheDog** [comment]
some other disposals notes, before (left) after (right)

<details><summary>pics</summary>
<p>
Main security room, sorting pipe pointing back into the output of a junction

image

Not yours, but this is an awful mess by robotics that has a 25% chance of shipping their packages elsewhere

image

Upper floor kitchen, missing this whole stretch which is needed for outgoing deliveries (and the kitchen output bin)

image

</p>
</details>

**Comment by FlufflesTheDog** [comment]
Floating light in chemistry, floating camera to the left
image

Janitor deliveries have a 50/50 shot of landing in the diner instead
image

Hos office/Security sorter isn't reachable from the mail loop (packages get stuck in a loop forever, don't return to cargo either)
image

And the kitchen has two tagged disposal chutes now, but only the top one can receive mail

**Comment by Ketrai** [comment]
@FlufflesTheDog Addressed! Amazed there are still broken lights x-x

**Comment by FlufflesTheDog** [comment]
Right sorter by the janitor office is facing the wrong way, spits trash back out of the diner bin
image
Same with security, hos + general trash get ejected right back out in general. And it's still not a part of the main loop, so things destined for here never arrive.
image

**Comment by Ketrai** [comment]
@FlufflesTheDog Should be addressed. Added apcs everywhere it makes sense. Disposal pipes should? Be fixed. Hopefully

**Comment by FlufflesTheDog** [comment]
Looks good to me

**Review by sqnztb — APPROVED** [review]
woof. looks good.

**Pull request merged**
