### PR TITLE
[MODULAR] Tarkon Tweaks set 1

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

- Changes a lot if not all of the windoors on tarkon to require tarkon access. No more free-running slimes. 
- Changes Tarkon Xenos Spawners to their own faction. Also modifies some spawning numbers
- A few holes within the mining cave. I guess they needed somewhere to dig their tunnels. 
- Adds cameras and camera console to Tarkon, Also makes the Xenobio console its own subtype instead of a var-edit.
- Adds Emergency-power Smes unit to Tarkon. Changes Tarkon Driver Smes units to not draw so much power.
- _**THE**_ Port-Tarkon Solar Array has lost its uniquity. 
- Changes some rando consoles to modular computers.
- Removes a pesky leftover set of sprites.
- Changes a tape and gives the correct tape in security.

## How This Contributes To The Nova Sector Roleplay Experience

Just kinda fixes some stuff and gripes. no more free bags for people abusing half-baked inclusions. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl:
qol: port tarkon has some emergency power to help at start
qol: port tarkon's ship has a much lower draw on spawn
qol: port tarkon engineers' inducer now spawns in backpack
balance: port tarkon xenos spawners rebalanced
balance: port tarkon xenos target hybrid xeno players now
add: port tarkon unique additions for access and cameras
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
I was gonna look at this to check it out in-game but I can't compile locally, so until I can get that sorted out, I'll check back later.

**Comment by Zenitheevee** [comment]
Latest change was to one of the modular bits, Kinda just changed a few tiles so there wasn't a glowing resin spawn under a window.

**Comment by Zenitheevee** [comment]
Changes to Spawners to tell people which jobs should require faction-specific characters until policy is touched.

**Comment by Zenitheevee** [comment]
Addressing Xeno Spawner feedback. Tunnels seem to occasionally bypass limit, and also will almost immediately spawn upon its xeno being killed, so they got bumped down to 1. Warren has been bumped down to 4 total. Nests down to 2. Nests and tunnels spawn at 40 second intervals now. 

Overall, Spawners should be much more tollerable to NOT go straight to attempted arson.

**Comment by Zenitheevee** [comment]
Changed Engineer's "Inducer" starting item to a pocket item to avoid over-write from quirk or loadout spawned items deleting it.

**Comment by Zergspower** [comment]
image
i should've never said anything... the end is neigh

**Comment by Zenitheevee** [comment]
> image i should've never said anything... the end is neigh

If it makes you feel better, Atleast i know how to add _**THE**_ to anything without typing _**THE**_ for the reasons to not type _**THE**_

**Review by Zergspower — APPROVED** [review]

**Comment by Zergspower** [comment]
Make sure policy reflects  restrictions on station/tarkon characters

**Comment by Zenitheevee** [comment]
> Make sure policy reflects restrictions on station/tarkon characters

Sadly the most i _**Can**_ do on that front is submit the _ideal_ tarkon policy and hope someone pushes it. 

I'm just getting the pods to nudge people in the direction while that gets worked out.

**Pull request merged**
