### PR TITLE
respectfully removes most of my content from the codebase

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

The reasons for the making of this pr would require at least one white guy video essay to explain in detail, so I won't bore you.

For a variety of reasons, from mistreatment of me and other contributors, to the administration situation of novasector, I don't want to be associated with the server in the ways that a lot of my content makes me, nor do I think any of my content is healthy for the server especially without maintenance from she who has made it.

Wherever I could, I replaced things removed with whatever in the codebase was closest, but for most of it I just deleted the lines especially since you people really, really do not use the seven nri or armadyne soldier outfits each that sit around and make debt.
## How This Contributes To The Nova Sector Roleplay Experience

Removes a lot of the barely or simply not at all maintained code debt generators I've left in the codebase. 
All of this content removed is also, frankly, not helpful to the roleplay environment of the server. All I receive from nova's players are complaints and hate about my content and so I think nobody will or should miss it being removed.
## Proof of Testing
It's ready once all the CI tests have no failures caused by me.

## Changelog
:cl:
del: Some stuff has been removed.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
(Do remove MilSim too as it was heavily reliant on your content, too; and won't really be complete using whatever /tg/ has.)

**Comment by Paxilmaniac** [comment]
That is for nova to figure out

**Comment by Floofies** [comment]
Hello! I don't usually leave my opinions in PR comments, but I feel I have to make an exception this time.

I don't feel like this PR is made in a respectful way, because there are 352 files edited and you have not given many details to describe what was removed/changed. Furthermore I'd like to say that I think plenty of people do like, and will continue to like this content regardless of your conclusions about it. I think there are enough edits being made here to justify a more diligent explanation at the very least.

As a related note, I'm not maintaining this repository, but I don't necessarily feel compelled to honor your request on my own downstream repository, regardless of perceived issues. I'd like to go on further about this and artists rights in public licensed projectsetc... But I don't think you need to read that, and I know you're not here because you're excited about the GPL.

Personally speaking, I also have some similar grievances with the same folks mentioned, and I've been harassed over my contributions too, but I think it's important to try and take care of myself and distance myself from things. I just really hope you can get some distance from the stuff that's making contributing suck for you. I am truly sorry about everything.

**Comment by Paxilmaniac** [comment]
> As a related note, I'm not maintaining this repository, but I don't necessarily feel compelled to honor your request on my own downstream repository, regardless of perceived issues.

I don't mind, Nova has simply failed to deliver on anything it promised and has harassed me and my friends as well as many contributors into leaving. If they want 2 disrespect people like this then I want them to get rid of all this stuff I've worked on for them. It seems only fair.

**Comment by Floofies** [comment]
Ok, that's understandable. Merge conflicts will cause me issues most likely, due to the number of edited files, so I'm not sure I could retain this stuff in my repo even if I wanted to. I think it would take a fair amount of work to separate out, so looking at the tech debt gives me a "punched in the gut" sort of feeling. I guess there isn't anything more productive for me to comment so I really just wish you luck and respect.

**Comment by GoldenAlpharex** [comment]
I'm locking this PR's comments ahead of time, because the last thing I want is something like this to become a drama-fest.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Alright, so, I'm going to step into the discussion here and say that, no, I'm not looking to see this PR being merged.

I'm not about to set the precedent that leaving the place means that you can pull back everything you've contributed out with you because that's an unhealthy precedent to set. Removing wholesale all of this content is not something I'm looking to do, there might be some things we'd be fine with removing, but not all bundled up together like this, definitely not. 

We can work on getting some things changed so that they're moved on from being attributed entirely to you, so you don't have to feel responsible for it all anymore. Still, as you've already left Nova, you shouldn't need to care about what people think of the state of the content you originally added. We'll take it up from here, as we do for any content being added by contributors to our codebase.

In general, we don't do removals of entirely separate features in the same PR, that goes directly against the principle of atomization, and I'm not looking to make any exception to that rule for this PR. That doesn't mean that atomizing this PR would get every/any removal PR merged either, for reference, but it's still an important point.

I've got nothing against you, I'm not forcing anyone to stay or to leave, but I'm heavily against the precedent this is trying to set. Once you contribute content to an open-source repository, you consent to others using your work and modifying it as needed, and your content becomes the repository's content once the PR is merged.

If you're getting harassed about some content you contributed to this repository, whether you're gone from the community or not, that's something that should be brought up to us, as harassment is not something that we allow in the community. You can get in touch with me directly if you'd like, and I'll handle that part of the situation because it's simply not acceptable.

**Pull request closed without merging**
