### PR TITLE
[MIRROR] Removes virologist job

### PR DESCRIPTION
**Pull request by NovaBot13**
Original PR: https://github.com/tgstation/tgstation/pull/82723
-----
## About The Pull Request
As the title says. Removes the job. Whole wing of medical is still there.

Screenshot 2024-04-17 041852

(MSO)
image

## Why It's Good For The Game
It's boring. It's so boring that when it decides to become unboring it just attempts to ruin the fun for everyone else
## Changelog
:cl:
del: Due to a need for company restructuring, virologists have been laid off by CentCom and doctors can optionally take their place.
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
its so joever

**Comment by GoldenGardens** [comment]
Golden, lets not merge this one

**Comment by Iamgoofball** [comment]
this should be merged because you guys literally have all of virologist rules-disabled

**Comment by Zergspower** [comment]
it's not getting removed, 'it's boring' can be applied to half the jobs in the game and they're still there.

**Comment by Iamgoofball** [comment]
@Zergspower you should consider providing some justification for this job remaining then because as it stands, the deck is stacked against it

**Comment by Iamgoofball** [comment]
like im just gonna say what everyone is thinking, virology's main use on skyrat/nova is as a private set of dorm rooms for medbay staff to engage in enterprise resource planning 

both this use case and "make the healing virus pill pile" use case are accounted for in the removal as virology's map space and machinery still exists for medical doctors

**Comment by Zergspower** [comment]
Nova isnt TG, what you think is 'fine' and 'standard' there isnt the same here. If you even played here you'd know we have trade mechanics in place with ghost roles relating to virus's as well.

**Comment by Iamgoofball** [comment]
unfortunately due to irreconcilable differences with one of your coup leaders i don't have a choice as to whether I can play at nova or not, but what I do know is that i extensively follow the code changes here and keep an eye on the wiki and

1. there's been no changes to virologist on the code-side so it's still in its' crippled state that it was on skyrat before you guys couped xyel
2. policy still expressly forbids any and all use of virology that isn't pure healing/abusing the 3 slot system to block other viruses, and viruses cannot spread in 90% of situations
3. even if you have sentient disease re-enabled, which I can clearly tell you don't based on the fact there's zero policy for it on the antagonist page at https://wiki.novasector13.com/wiki/Antagonist_Policy, it's a terrible antag we want to remove at /tg/ for being so immensely boring and also just broken in the unfun "you die when you spawn as it" way that it was on the chopping block alongside virologist before MSO stepped in

chrome_fKy38mSB5R

about 75% of the symptoms accessible in virology are simply blocked, in full, by your policy as antagonists aren't allowed to bypass this

virologist is just a trap job for newbies to step in, not realize they've made a mistake by accidentally leaving coughing in their healing virus, and then get banned for grief at this point

additionally, you and I both know this @Zergspower but fundamentally not much has actually changed since the coup occured and you know I have plenty of experience on skyrat, so I think it's incredibly immature to try to pull the "you don't play here" card when the topic of discussion literally has not changed since the coup occured

_**additionally**_, pretending that you aren't /tg/ when you actively mirror our work every single day and piggyback off of all of our work is, frankly, kinda insulting to myself and the hundreds of /tg/ developers over the years who do the incredibly hard work of building the base for your codebase that you mirror with mirror PRs every single day, like c'mon, if you wanna claim you're not /tg/, hard fork and quit mirroring our work, otherwise accept that sometimes /tg/ is right about things and this is one of those times

we aren't trying to tell you that you need to follow /tg/ 100% lockstep, what we're trying to tell you is that you're ignoring the lessons learned on the codebase you aggressively borrow every single pull request from

we're not all LRP barbarians at /tg/, we run a fairly healthy RP server at Manuel and we understand how to do design for roleplay, we're officially an MRP codebase at /tg/ after all per orange man proclamation. When we say "hey, virologist's time to go is now", we're not saying it because we hate roleplaying with virology, we're saying it because virologist is just really bad and we'd like to put something more interesting from a gameplay and RP perspective where virologist is. Look at jobs like Coroner and Psychologist if you want proof we care about adding fun RP jobs to the game that don't have gameplay but are still fun.

**Comment by Iamgoofball** [comment]
also, yeah, it's not really off topic to discuss enterprise resource planning in relation to virologist because that's an added use-case of virology having a private lab, multiple private bedrooms, and a private break room dedicated to it on the map, people love getting their enterprise resource planning on in there and the doors being changed to Medical Doctor access improves medbay staff access to the area

not trying to shitpost here, I'm 100% serious, this is a positive change on that front

**Comment by YehnBeep** [comment]
> we're not all LRP barbarians at /tg/, we run a fairly healthy RP server at Manuel and we understand how to do design for roleplay, we're officially an MRP codebase at /tg/ after all per orange man proclamation. When we say "hey, virologist's time to go is now", we're not saying it because we hate roleplaying with virology, we're saying it because virologist is just really bad and we'd like to put something more interesting from a gameplay and RP perspective where virologist is. Look at jobs like Coroner and Psychologist if you want proof we care about adding fun RP jobs to the game that don't have gameplay but are still fun.

> not trying to shitpost here, I'm 100% serious, this is a positive change on that front

I'll chance a serious response then.

So, since you bring up coroner, let's start with saying having that as a separate job from MD adds far less than viro - and when someone isn't playing it (which is often in my experience), it actively obstructs MDs from contributing to research requirements during those early round moments when MDs don't have a lot to do anyways.

And I'm not just saying that to dunk on coroner. Now, let's look at viro. On Nova, virologists/pathologists often put out anywhere from 3 to 6 variants of healing viruses to basically cover the range of species and preferences (compare to TG, where in my experience, it's rare even 2 variants will be created). If there's a gap in those offerings, or no one playing virologist, ghost roles can step up and offer there own - for compensation or good will.

You may disagree with the value of such gameplay/interactions, but it _does_ create interactions. If you feel it doesn't create enough, weeeell... there's other jobs that have targets on their back on that front, arguably bigger ones at that. If it's fine for them to exist... _shrug_

But is it really so important to you that Nova follow the trends of Bee and TG? Why not just accept that a different community may have different values?

**Comment by CandleJaxx** [comment]
i think ppl saying "virologist is still needed here" are coping tbqh. we don't really benefit from it at all besides the odd nctr. just let medical doctors do it

**Comment by nikothedude** [comment]
i just think it doesnt really matter

**Comment by Iamgoofball** [comment]
```On Nova, virologists/pathologists often put out anywhere from 3 to 6 variants of healing viruses to basically cover the range of species and preferences (compare to TG, where in my experience, it's rare even 2 variants will be created). If there's a gap in those offerings, or no one playing virologist, ghost roles can step up and offer their own - for compensation or good will.```

This isn't actually enjoyable for any players because there's no room for variation; you have to follow a very specific set of guidelines for what symptoms to use to accommodate the slime/no slime divide because any deviation will get you banned. This is one of those situations where you guys really just need to admit that maybe virologist isn't a good fit for Skyrat/Nova. You have NIFs or nanites or whatever, and a massively expanded selection of medicine available for purchase from Cargo. Those are way more interactive and interesting than just having passive healing 24/7.

You don't get to roleplay as a cool virologist engineering diseases to help the crew, you're just following a spreadsheet of what to do to get the specific slime safe healing virus everyone wants, times three to fill all 3 virus slots, then calling it a day.

This isn't roleplay, this is just spreadsheet following. Nobody enjoys spreadsheet following.

You also didn't even address the bigger problem with virology that's Skyrat/Nova specific, 75% of it is disabled on a policy level and 20% of it is disabled on a code level because basically of virology's gameplay mechanics fit your ruleset. Let's face it, the only reason anyone is arguing for keeping virology is because it would be changing the norm and it would break people's pre-existing routine. You just rambled about community values instead of addressing that clear cognitive dissonance.

### I ask again: If Virology is so important to the foundation of Skyrat/Nova, why is 75% of it blocked by policy and 20% of it blocked by code changes and the Virology-Specific antagonist disabled in the configuration with no policy for it written on the page?

***None of the virology machinery or code is going away.*** Medical doctors get Virology access. If they want to make the 3-6 healing viruses you describe, they can do so. There is nothing stopping them. This PR even increases the MD slots by 1 on both spawn and total so they can spawn in. I made a PR to add Virologist to medical doctor's job titles but it was closed without any reason being given for some reason alongside a PR to fix the compile errors on 3 maps as a result of this PR, so I've escalated that to @GoldenAlpharex for review.

**Comment by Iamgoofball** [comment]
And for the record, "we're not /tg/" is, once again, a bad argument when you mirror all of our work every single time a pull request is opened to your repository. It is akin to a teenager being unable to justify why they're smoking cigarettes with any other reason than "dad told me not to smoke cigarettes and I'm not my dad". I've been saying this for years and received nothing but dismissive remarks from Skyrat/Nova's staff as a result, but they never actually disproved my statements here. 

At Skyrat, this was because it was run top down as a dictatorship with absolute rule coming from the host, so gut feelings and random decision-making was par for the course. The coup was supposed to fix that and bring about a new, democratic rule where people in the community had actual input, so what's Nova's excuse?

You are still mirroring and merging just about every /tg/ PR. You take in 99% of our game design changes. You take in all of our bugfixing and our infrastructure buildout and use our TTS server. I didn't like it when your higher up staff treated 

I don't understand why every single codebase that forks /tg/ to be their own cool thing continues to insist on copying every single PR we make to our repository at /tg/ in real time, and then proceeds to shit all over us by pretending we have no idea what their needs are or what their codebase is like when we make design decisions at /tg/. Plenty of our admins played at Skyrat and I'm sure a few still play at Nova despite the incidents that have occurred. Plenty of our coders played at Skyrat and I'm sure a few still play at Nova despite the incidents that have occurred. 

This "/tg/ doesn't know what Skyrat/Nova/Bubber/Any downstream wants" nonsense is pervasive, without actual evidence, and just plain offensive to /tg/ as a community given the very, very large amount of work we do for you guys pro bono, for free, with no expectations of anything being returned. 

We pay attention to the downstreams. 
Our host actively supports Nova, Skyrat, and TGMC with TTS, albeit **_you guys do chip in to help pay the bills on that and we do very much appreciate it_**. 
We actively take downstreams into account when we merge pull requests at /tg/ to clean up code and make it more extensible. 
It hurts every time I see someone do that and then I come down here and see someone complaining on a PR about how /tg/ doesn't know what they're doing.

If you wanna smoke cigarettes even though we've determined that smoking cigarettes is unequivocably bad for you, move out of our house and hard fork, don't just sit there in front of us smoking cigarettes and blowing the smoke in our face while talking about how your lungs are actually fine, really, while hacking your lungs up in private.

**Comment by nikothedude** [comment]
tg can make their decisions, we can make ours, we just need to make sure to not say tg's design is bad beacuse who are we to judge lol

**Comment by chemistrymain3** [comment]
@YehnBeep 

'Nova isn't TG' isn't an argument that's important to make in this case

it applies for balance concerns, where someoen might say 'but that's not balanced' and you point out nova does not have the same round times or combat

virologist is more or less as functionally irrelevant here as it is on TG- all the mechanics can remain, but there's no reason not to roll it into the MD job and make it an alt title

actually, it's even more functionally irrelevant here, since most of the job mechanics it's meant to deal with are basically _gone_

**Comment by YehnBeep** [comment]
So, here's a question, then:

If virologist is rolled into MD as an alt title, and a player takes MD with this alt title: Will people/admins be OK if this technically-MD doesn't know surgery, isn't interested in doing/learning surgery, etc etc?

Technically speaking, these arguments could be applied to chem as well. Why not just let MDs into the pharmacy and chem lab to make their own meds? What's really the value of having it separated out with separate accesses?

To some extent roles are more than just mechanics, they also set expectations of knowledge and duties.

And, this isn't a "Don't merge this PR!" post. If the powers that be really feel virologist's existence isn't merited, I'm not losing any sleep over it. But I also feel "Bee and TG did it, get with the times Nova!" isn't much of an argument. "There aren't enough mechanics", y'all sort of undermined yourselves by pointing out jobs like coroner and psychologist, which could also easily exist as alt titles (But a psych player might not be interested in surgery et al too).

If people are having fun with the job and surgery or more traditional MD duties aren't their cup of tea... _shrug_
What's the big deal with keeping it, who cares what Bee/TG did?

And if they aren't, then... _shrug_
Sure, might as well get rid of it, but still, that's a reason itself - who cares if it's in line with the others or not?

**Comment by OrionTheFox** [comment]
> i think ppl saying "virologist is still needed here" are coping tbqh. we don't really benefit from it at all besides the odd nctr. just let medical doctors do it

The best part of this is that goof is literally trying to propose ways **to keep virologist** without being non-modular and gross about it. The backlash he's getting is actually extremely upsetting.

**Comment by GoldenGardens** [comment]
After reading everything Goof has said, I think my opinion has changed on it, and I gotta agree with him

**Comment by SciDragon** [comment]
Out of scope, perhaps, but I always wondered why virologist and coroner weren't just rolled into one "pathologist" job as both deal with death and disease.

**Review by Zergspower — APPROVED** [review]

**Review by Zergspower — APPROVED** [review]

**Comment by TripleShades** [comment]
So the other two prs concerning this here will get reopened and merged, right?

**Comment by CliffracerX** [comment]
> So the other two prs concerning this here will get reopened and merged, right?

This is likely being merged to then handle a proper revert and modularization.

**Comment by Iamgoofball** [comment]
>If there is an actual compelling argument for it then by all means but so far I have not seen anything like that
@vinylspiders
I provided multiple, repeated explanations of why Virology is a poor fit for Skyrat/Nova citing your rules, citing your policy, and citing the code changes you've had to make to the feature for it to even remain active.

It was ignored repeatedly and not addressed. Here are multiple posts from me elaborating on the actual design issues with virology in relation to Skyrat/Nova:
https://github.com/NovaSector/NovaSector/pull/2062#issuecomment-2068191034
https://github.com/NovaSector/NovaSector/pull/2062#issuecomment-2067764731

**Comment by Iamgoofball** [comment]
@vinylspiders 

>You can say the same thing about a lot of the TG features. It's not unusual for RP servers to have policies regarding things that are annoying/disrupt roleplay. There is still enough there that isn't against policy.

We really can't say the same about a lot of the TG feature set, though. We've made a significant shift over the last decade to stop adding admin-only things and ensure that if we're putting something into the game, it's because we want it to be in the game and properly designed, not just be a toy in an admin's toolbox. That's the old SS13 way of designing things back when we had zero admin oversight and SoS did shit like randomly rename Captain to Cobra Commander for a shift and break the Captain job as a result.  We've all moved on from that way because it's simply not feasible or sustainable to keep an enjoyable roleplaying game going with this design philosophy.

It's understandable to keep a few things on a leash, but when damn near the entire feature needs this much of lock and key on it along with pre-emptive strikes against it, why bother keeping it in the first place? This is a common flaw in the Skyrat/Nova design dichotomy that results in a lot of bad changes getting done temporarily or, god forbid, not fixed ever. Continuing to layer policy after policy on top of what is fundamentally a badly designed system at its core is not a solution, it's applying a repeated band-aid. 

>I don't see why we need to cause such a disruption when as you mentioned yourself, the code is still in the game anyway.

It's a gradual shift. We will eventually at /tg/ replace Virology with something more interesting on the maps now that the space has finally been freed up. When that eventually happens, because it will, when the mirror PR comes down the pipeline you will now be stuck in the incredibly obnoxious space of having to maintain 5-7 map template patches to re-add Virology's lab to the stock /tg/ maps, connecting it to the power grid, connecting it to atmospherics, etc. alongside whatever new job or feature set we decide to implement in its place. 

Maybe we decide Medical needs a Veterinarian who focuses on simple/basic animals. Maybe we add Orthopedics. Maybe we add Dentistry. Something will eventually go there because there's a lot of demand for something new and interesting in Medical, and Virology's lab space is now up for grabs.

Are you sure your maptainers are ready for that level of map maintenance? They balked and backed down and said it was too much work when I proposed departmental guard office overrides, and that was singular rooms and involved no changes to atmospherics or powernet piping/cabling. Virology's an entire complex attached to most maps with the maintenance paths occasionally built around its existence.

If you had simply removed the Virologist job slot, added a medical doctor slot, and put Virologist on the MD job titles list, your players could have time to transition to understanding that Virology is a side thing now rather than important enough to be a mainline job, and when the inevitable PR to move the virology equipment into a side room in medical rather than taking up a massive chunk of map footprint for a job that no longer exists occurs, you will be looking back on this with regret for not taking the opportunity to get this done sooner.

>That's an opinion? Some people don't think that way. And personally I would prefer to see the system overhauled to be more interesting and interactive with other systems rather than all these very half-assed attempts at complete removal that TG has tried to do in the past.

We'd all like to see the system overhauled to be more interesting and interactive, but at some point you have to accept that the core premise is not particularly fun or interactive without a serious fundamental re-design, and the people who are upset now about the removal will be upset still at said serious fundamental re-design. We had long, detailed discussions about this at /tg/ before settling on this approach mostly only because of host fiat. We would've axed player-created viruses entirely if it was not for MSO insisting the system remain and having the nuclear button to ensure it'd occur.

Fundamentally, players don't know what they want. Ask any game designer in the AAA space. They will aggressively optimize themselves into ruining their own fun before you can even say the word go if you let them, and Virology is designed in such a way that lets players optimize the fun out of it completely.

I didn't want to re-hash virology's core problems in here because I assumed everyone here understood the fundamental design problems with the virology concept as it stands, but these are the three main fundamentals that make Virology an untenable feature, especially for an HRP environment like Skyrat/Nova:

1. People just do not like sitting around in Medical waiting to be treated. They want to go do other things like engage in enterprise resource planning in the sauna or work on their build project or go arrest crewmembers or smoke the fattest blunt you've ever seen, not wait around in medical for someone to press a few buttons and treat them. The anger becomes exponential with the number of other people in medical also waiting for the exact same thing; every single patient in medical that can see other patients will assume that all of those other patients are in line ahead of them, and the anger will go off the charts. Nobody likes a crowded medbay and Viruses are designed to create a crowded medbay of people very urgently needing something to either let them leave medbay or stop them from dying and thus being stuck in medbay even longer. _**This is, by far, the biggest issue with Virology and ties back to what irritates a lot of players on HRP servers when they end up in Medbay for extended periods of time.**_

2. Setting aside how much of Virology is hard disabled via rules and code, the actual mechanics of virology are obscure, clunky, and just a shitty slot machine time gate for passive free healing. You spin the food/plasma wheel for the healing symptoms and the things you can neutralize to make them free, and then you do that 6 times over, and then you do that another 3 times to fill all 3 virus slots and then the whole station is now immunized to every potential bad virus and they're all passively healing. It's fun optimization to the maximum, people aren't gonna go buy meds from cargo or seek treatment from doctors if they can just passively heal themselves. 

3. If you want everyone to just have passive healing, just add passive healing to the game as a baseline feature. Going about it in this roundabout way just makes for a confusing and awkward gameplay experience. Bastardizing Virology into the crew-available passive healing option is just dumb and a weird, unintuitive approach that makes me think of janky mods for video games and not a game where direct source code access exists and can be modified to redesign things.

4. Treating viruses is also literally a slot machine; you pull the lever and find out if it's "i can cure this with a pile of 1u sugar pills" or "i'm going to be stuck in plumbing hell for the next 30 minutes crafting the Fartonium Inverse that needs to be used to cure this disease". There's no roleplay involved in curing a virus, nor is there roleplay involved in making it. It's checking off a checklist of gambling no matter which side you're on, and the players are trapped in between it.

5.  Virology takes up so goddamn much map space on every map that it means we've got no other room for the vast majority of jobs we might want to add to Medical because there's practically five to six rooms worth of mapspace dedicated to 1 (one) job that barely utilizes any of it because they just sit in one spot and touch two adjacent machines.

**Comment by Iamgoofball** [comment]
Basically, there's plenty of ways to get what Skyrat/Nova actually wants out of virology *without* trying to staple what you want to the dead corpse of a job that's been rotting away for 15 years, y'know? I think that should be explored instead of just modularizing Virologist temporarily, because we all know temporary bandaids are the most permanent.

**Comment by Iamgoofball** [comment]
went and dug these up too, for folks reading about the history of virology, the debates over the job among /tg/'s maintainers:
https://discord.com/channels/326822144233439242/808425762217656330/1176974673590890636
https://discord.com/channels/326822144233439242/808425762217656330/1175827923169706016

**Comment by Redrover1760** [comment]
Goof please chill its just a video game. Manuel isnt an rp server, I'd know, as it has no flavor text, roleplay standards, character loadouts, roleplaying people, etc.

**Comment by Iamgoofball** [comment]
Manuel is explicitly a medium-roleplaying server with dedicated roleplaying rules.

**Pull request merged**
