### PR TITLE
Removes two unmaintained modular space ruins

### PR DESCRIPTION
**Pull request by OrionTheFox**
## About The Pull Request
Removes Ghostship.dmm and Salvagepost.dmm
After watching a few playthroughs I've determined that these ruins are no longer functioning as I originally intended, between visual bugs and general balance/flow jank. I'll likely redo them upstream at some point.

This PR affects ONLY these two ruins. Anything that others have begun using elsewhere has been left (such as Spaceship Walls or the fluff pre-recorded tapes).

## How This Contributes To The Nova Sector Roleplay Experience
Removes unmaintained, unmonitored, and broken code/ruins.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

I'm not taking a second screenshot for Ghostship because I use the built-in snipping tool and that makes me feel gross
</details>

## Changelog

:cl:
del: Removed two unmaintained modular space ruins, Ghostship and Salvageyard
/:cl:

### CODE REVIEW

**Comment by Zenitheevee** [comment]
... Salvage post was that one large ruin that was just a giant Hardlight Ship Breakers reference right?

**Comment by BigAganoo** [comment]
> ... Salvage post was that one large ruin that was just a giant Hardlight Ship Breakers reference right?

Both were shipbreaker references. Salvage post was the big one with the cutter's pod and ship. Ghost ship was the one with the AI nodes that scream at you when you break 'em.

**Comment by Zergspower** [comment]
I'm fine with salvage post being removed as i had pegged that in my notes of needing an overhaul already, ghostship however can stay as it's a truly unique ruin that's beyond the generic ones we normally see

**Review by Zergspower — CHANGES_REQUESTED** [review]
go ahead and knock out salvage but leave ghostship

**Comment by OrionTheFox** [comment]
@Zergspower I will not be making further changes. I am removing both of my ruins as they are unmaintained, no longer meet my vision for them, and have issues that will not be resolved without full reworks.

**Comment by Zergspower** [comment]
> @Zergspower I will not be making further changes. I am removing both of my ruins as they are both unmaintained, both no longer meet my vision for them, and both have issues that will not be resolved without full reworks.

What exactly is your vision for the ghost map, i'm again not willing to approve the removal of it but that doesnt mean i or you couldnt look at it and address the issue

**Review by Zergspower — APPROVED** [review]
Will readd ghostship

**Pull request merged**
