### PR TITLE
[NON-MODULAR] Disable quirk points

### PR DESCRIPTION
**Pull request by Floofies**
## About The Pull Request

This PR functionally disables several chunks of TG code which implement quirk points balancing, and some Nova Sector code for augments which does the same. I made the changes by commenting out the lines in an auto-merge friendly way. 

The changes in this PR allows players to pick positive quirks and augments without picking any negative quirks. The quirk points balance is also hidden in the Character Preferences window, while the values of quirks remain visible.

## How This Contributes To The Nova Sector Roleplay Experience

This PR reflects the broader community intent to make quirks a more cohesive system for character creation, and remove balancing of quirks via points.

Other methods of balance can be implemented instead of a points system, [such as PRs which directly balance individual quirks.](https://hackmd.io/@internetizen/quirk-tweaks-3)

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

Screenshot 2024-01-15 222123
Screenshot 2024-01-15 222057

https://github.com/NovaSector/NovaSector/assets/17753498/1b38f17a-4708-4e88-9883-f2d4ab2e62be

</details>

## Changelog

:cl: A.C.M.O.
balance: Functionally disabled points for Quirks and Augments+, allowing players to select any quirk or augment without first picking a negative.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Nobody uses EMPs, though

**Comment by Nerev4r** [comment]
> EMPs are lethal enough to random people that no one is just going to use one, and the CME event was removed.
> 
> The tools aren't inherently weak either, as they a.) exist and take up no storage, which is infinitely better then them not existing and b.) some of them are weapons.

image

**Comment by Floofies** [comment]
Looking at what's up with the TSX linter

**Comment by CandleJaxx** [comment]
DOWN WITH BALANCEJAKS

WE, AS A SOCIETY, HAVE PROGRESSED PAST THE NEED FOR NEGATIVE TRAIT REQUIREMENTS

**Comment by ApplePlastic** [comment]
can kill the ways of putting up with shitty balance with great friends

**Comment by W4rd3nn** [comment]
My drill is the drill that will pierce the quirk balance.

**Comment by Floofies** [comment]
Thinking of making a TG config for this instead

**Comment by Floofies** [comment]
Adding config `DISABLE_QUIRK_POINTS` to TG instead

**Pull request closed without merging**
