### PR TITLE
Adds new station map Nebulastation 

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

Adds a completely brand new multi-z station map "NebulaStation".  New areas and few exclusive map shuttles (ferry, mining, arrival, evac, cargo)
Few example screenshots
StrongDMM-2024-07-19 20 53
15 StrongDMM-2024-07-19 20 51
41

image

image

image

image And more...

## Why It's Good For The Game

New maps are always good for the game

## Changelog

:cl: 
add: Nebulastation, new station map
/:cl:

### CODE REVIEW

**Comment by KikoWen0** [comment]
Nothing personal, but I'd like my work to not be associated with any 18+ servers if possible. Thanks.

**Comment by Zergspower** [comment]
> Nothing personal, but I'd like my work to not be associated with any 18+ servers if possible. Thanks.

I can remove your tag in the CL, but not having a map will cause constant CI issues as we're a downstream of TG

**Comment by GremlinSeeker** [comment]
> > Nothing personal, but I'd like my work to not be associated with any 18+ servers if possible. Thanks.
> 
> I can remove your tag in the CL, but not having a map will cause constant CI issues as we're a downstream of TG

I don't see how that's an issue when all the PRs coming in are manually cherry picked from TG to get merged, for instance nebula right now.

**Comment by sqnztb** [comment]
Initial automapper plugs are in.

NT Rep - 
image

Barber - 
image

Cryo - 
image

Armory - 
image

Arrivals - 
image

Button, which yes, I tested. Works fine, though with a 2-Z engine room you ABSOLUTELY do not want to press it - 
image

**Comment by KikoWen0** [comment]
I agree with GremlinSeeker here, CI has nothing to do with a map?? It's a lame excuse to push something through.

**Comment by kittysmooch** [comment]
> I agree with GremlinSeeker here, CI has nothing to do with a map?? It's a lame excuse to push something through.

this repo has already denied people the right to not have their content associated with it, though you should fight them on it anyway it's probably going to continue falling on deaf ears.

**Comment by GoldenAlpharex** [comment]
> > > Nothing personal, but I'd like my work to not be associated with any 18+ servers if possible. Thanks.
> > 
> > 
> > I can remove your tag in the CL, but not having a map will cause constant CI issues as we're a downstream of TG
> 
> I don't see how that's an issue when all the PRs coming in are manually cherry picked from TG to get merged, for instance nebula right now.

Hi there.
We've been mostly batching /tg/ PRs in bigger PRs, instead of individual ones using the mirror bot as we used to in the past, in order to try and reduce the workload for maintainers, especially when it comes to waiting on CI to pass on twenty PRs at a time, which incurs much longer delays. We've been quite busy these past few weeks, and unfortunately have been falling behind on said batch PRs, and during that time other people have been slowly helping picking up the slack. We're starting to pick up steam again and are planning on catching up with all of what we've missed in the last month or so, but that takes time.

What you're seeing here is simply Maptainers working to help with that, within their area of expertise, because it makes a lot more sense to have a separate PR to add a new map, than to have it bundled with 50 others. We can't simply _skip_ adding a map, as there's invariably going to be more and more PRs on /tg/ that touch this map, be it individually or batched in with other code/map changes. This means that we'd have to spend a lot of time every time one such change occurs, manually removing the changes that target Nebulastation from the PRs, and that's a lot of added workload to our pipeline. Not only that, but every time a change is made to the .dmm file for the station, it's going to try to add it in full to the repository, as Git notices that we're actually missing the file.

Basically, the bottom line here is that, realistically, avoiding to add an entire map to our repository, while still remaining a downstream of /tg/, would result in a very annoying increase in workload that will only get worse as time goes on. This isn't anything personal, we're not trying to steal credit for someone else's work, be disrespectful to them or their work or anything, but it's simply not very realistic to ask downstreams of a popular codebase that's _known_ for having many downstreams, to avoid getting a specific map from their upstream, as that's something that's unfortunately included with contributing to such a codebase, downstreams are bound to receive content you've made, one way or the other.

That being said, as Zergs has said, we can definitely work into making sure your name doesn't come up, as much as we can, so as to avoid you being linked to the repository.

I hope this makes sense.

**Review by sqnztb — APPROVED** [review]
Probably ready to go now that it won't it cause any CI meltdowns. I think. I hope.

**Comment by KikoWen0** [comment]
> we can definitely work into making sure your name doesn't come up, as much as we can, so as to avoid you being linked to the repository

You can also work into making sure my map will be turned off in your configs, as that definitely won't interfere with any upcoming PRs

**Comment by LemonInTheDark** [comment]
> You can also work into making sure my map will be turned off in your configs, as that definitely won't interfere with any upcoming PRs

This conversation seems to be the result of talking past each other. What you posted initially seems like it is being read as "I don't want my name tied to your project" rather then "I don't want you using my work" which seems like how it was intended. If I'm wrong about this then @GoldenAlpharex should be more direct w you about it IMO.

I think it is fair and understandable to not want your identity linked to horny, especially if it makes you uncomfortable.
I do not think it is right to like, manage how your work gets distributed though. The map isn't you it's something you've put a lot of time into, etc.
I really do not like the idea of our downstreams being socially prohibited from porting a feature/sprite/map because the person who made it doesn't like them. It strikes me as harmful to the distributed nature of the game and the growth of other contributors.  When something is pr'd ownership and control of it is loosened and I don't think it's healthy for the community to assert soft authority in this way.

**Comment by Draggeru** [comment]
> Nothing personal, but I'd like my work to not be associated with any 18+ servers if possible. Thanks.

Not how open source projects work. Contributing to TG means you also contribute to its downstreams

**Comment by MitztheKat** [comment]
There's no toilets in perma.

**Pull request merged**
