### PR TITLE
[what a kawaii morning!] Snail Resprite, Brought To You By Supugaru

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
Thank you again!!!
image
image
image

This resprites snails to look a little less ass. Particularly their legs were pretty bad.

## How This Contributes To The Nova Sector Roleplay Experience
I love when things look good, and supugaru did a hell of a job.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
It's in the intro.  
</details>

## Changelog
:cl:
image: Snails have been resprited, as well as the ivory versions of their shells to allow for more accurate recoloring.
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
image
image
image

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Could we just get a before/after, so I can better compare the sprites? Thanks!

**Comment by Nerev4r** [comment]
> Could we just get a before/after, so I can better compare the sprites? Thanks!

image

Here is the miserable form of the old sprite.

**Comment by Jureiia** [comment]
🐌👍

**Review by GoldenAlpharex — APPROVED** [review]
It's snailin' time. 🐌 👍

**Pull request merged**
