### PR TITLE
Restocking part I, a semi-replacement of the Szot Dynamica guns we already have.

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request
Replaces all the sprites with either slightly edited, or mostly-replaced versions of their old forms, to distance us further from the PR they came from (https://github.com/Skyrat-SS13/Skyrat-tg/pull/24304) while also changing their desc to be more vague, and applicable to the station over vaguely referencing conflicts that only dubiously might have happened.

---

Also generally buffs a few of the under-performing calibers, and guns, to be inline with the rest, instead of completely dogass (the slonce) and right-of-the-cusp of being good, but outdone by everything else (wylom).

also gives the miecz some woundchance, because it turns out, using non-AP ammo against armored people for the wounds was actually just better. (plus a minor damage buff)

Also makes the bobr longer, for no good reason, and debullpups most of the guns because I started doing it and it was a bit to funny to stop.

## How This Contributes To The Nova Sector Roleplay Experience

Consistency is king, and these bad boys are exactly as inconsistent as you'd expect.

But flavor choices are great, and despite these having a pretty solid vibe, it was almost knee capping yourself to try and use them.

(forgive the editor screenshots, i'll get better ones once I put it up)

<details>

bobr
image
Slonce
image
Gwaizda
image
Wylom
image
Lanca
image
Meicz
image

</details>

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

386289928-97b5ff34-fda8-4767-985a-a89869fa1f89

</details>

## Changelog

:cl:
sprite: Replaces all the 'szot dynamica' weapon sprites, with slightly or heavily edited variants.
code: Replaced all their desc's with stuff that better fits the station, and removes mention of non-cannon conflicts and military behavior.
balance: Slight rebalance of most of the szot-dynamica guns, or calibers, to be equal to the solfed variants, instead of a flat downgrade.
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
and before anyone asks, the miecz cannonically has a banana mag now 
image

**Comment by LordHookie** [comment]
The Wylom has no difference between its bare and armored wound chance. I think this would be unique to it. Is this intentional?


Also, some minor typos in weapon descriptions:
 _"**Further on, its claims of fauna hunting use, most people just picking up the thing could figure out the real use.**"_ needs to be rewritten entirely
 _"...quickly being eaten up by both **militia's** and..."_ should be plural (militias)
 _"...**it's** cheap-and-rechargable packs..." / "...cousin to **it's** starting frame." / "**it's** classification as a rifle"_ should all say "its", "it's" is a conjunction
 misplaced commas in _"model replacing the grip with a**,** standard rubberized..."_ and _"A short barrel**,** weapon riding..."_
  _"**wood-substitute** material is known"_ is not capitalized
  _"...**And** to not use it if you arent..." is capitalized and should not be, aren't needs an apostrophe
  _"...**And** a scope."_ is capitalized and should not be
  _"long barrel"_ and _"short barrel"_ should both be hyphenated i'm pretty sure

**Comment by RatFromTheJungle** [comment]
> The Wylom has no difference between its bare and armored wound chance. I think this would be unique to it, and would make it so the .60 Strella is not any more dangerous to you (wound-wise) if you're naked than actually in armor. Is this intentional?
> 
> Also, some minor typos in weapon descriptions: _"**Further on, its claims of fauna hunting use, most people just picking up the thing could figure out the real use.**"_ needs to be rewritten entirely _"...quickly being eaten up by both **militia's** and..."_ should be plural (militias) _"...**it's** cheap-and-rechargable packs..." / "...cousin to **it's** starting frame." / "**it's** classification as a rifle"_ should all say "its", "it's" is a conjunction misplaced commas in _"model replacing the grip with a **,** standard rubberized..."_ and _"A short barrel **,** weapon riding..."_ _"**wood-substitute** material is known"_ is not capitalized _"...**And** to not use it if you arent..."_ is capitalized and should not be, aren't needs an apostrophe _"...**And** a scope."_ is capitalized and should not be _"long barrel"_ and _"short barrel"_ should both be hyphenated i'm pretty sure

i'll get around to cleaning them up soon ™️ by the time i got through the onmob's, I just wanted to fling the PR up as fast as possible so people could glance it.

**Comment by RatFromTheJungle** [comment]
> The Wylom has no difference between its bare and armored wound chance. I think this would be unique to it, and would make it so the .60 Strella is not any more dangerous to you (wound-wise) if you're naked than actually in armor. Is this intentional?

and yes, to a degree, 70 damage is going to be rolling for alot of wounds on it's own.

**Comment by annikaRU** [comment]
> > The Wylom has no difference between its bare and armored wound chance. I think this would be unique to it, and would make it so the .60 Strella is not any more dangerous to you (wound-wise) if you're naked than actually in armor. Is this intentional?
> 
> and yes, to a degree, 70 damage is going to be rolling for alot of wounds on it's own.

The argument can be made its a literal anti-material rifle, you could increase the price heavily to compensate for the damage it would do

think of a 50 BMG rifle, this was meant to be the equivalent of that

**Comment by RatFromTheJungle** [comment]
> > > The Wylom has no difference between its bare and armored wound chance. I think this would be unique to it, and would make it so the .60 Strella is not any more dangerous to you (wound-wise) if you're naked than actually in armor. Is this intentional?
> > 
> > 
> > and yes, to a degree, 70 damage is going to be rolling for alot of wounds on it's own.
> 
> The argument can be made its a literal anti-material rifle, you could increase the price heavily to compensate for the damage it would do
> 
> think of a 50 BMG rifle, this was meant to be the equivalent of that

money is metaphorically irrelevant, 2k-10k is almost no difference except a 15m time investment, giving it a massive boost in wounds would just lead to it always rolling the most severe ones (with a fair chance of disembowling on the second shot) and that's not something i'd want running around willy-nilly

**Comment by RatFromTheJungle** [comment]
fixed wylom sprite not having the mag seperated; and tested now
image

**Comment by RatFromTheJungle** [comment]
image

**Comment by RatFromTheJungle** [comment]
and the comparison screenshot: 
image

**Comment by RatFromTheJungle** [comment]
i'm gonna do one more set of changes:
- let the wylom fit on armor slot again
- either weaken the miecz, or make it bulkysized

**Review by GoldenAlpharex — APPROVED** [review]
Been test-merged for a little while and it's been going well, let's get this in properly.

**Pull request merged**
